local addonName, addon = ...
local _G = _G

-- luacheck: globals UIDropDownMenu_AddButton

addon.combatProtected = {
	-- List of cvars that can't be modified in combat
	["alwaysShowActionBars"] = true,
	["colorblindSimulator"] = true,
	["colorblindWeaknessFactor"] = true,
	["daltonize"] = true,
	["fullSizeFocusFrame"] = true,
	["garrisonCompleteTalent"] = true,
	["garrisonCompleteTalentType"] = true,
	["nameplateClassResourceTopInset"] = true,
	["nameplateGlobalScale"] = true,
	["NamePlateHorizontalScale"] = true,
	["nameplateLargeBottomInset"] = true,
	["nameplateLargerScale"] = true,
	["nameplateLargeTopInset"] = true,
	["nameplateMaxAlpha"] = true,
	["nameplateMaxAlphaDistance"] = true,
	["nameplateMaxDistance"] = true,
	["nameplateMaxScale"] = true,
	["nameplateMaxScaleDistance"] = true,
	["nameplateMinAlpha"] = true,
	["nameplateMinAlphaDistance"] = true,
	["nameplateMinScale"] = true,
	["nameplateMinScaleDistance"] = true,
	["nameplateMotion"] = true,
	["nameplateMotionSpeed"] = true,
	["nameplateOtherAtBase"] = true,
	["nameplateOtherBottomInset"] = true,
	["nameplateOtherTopInset"] = true,
	["nameplateOverlapH"] = true,
	["nameplateOverlapV"] = true,
	["NameplatePersonalHideDelayAlpha"] = true,
	["nameplatePersonalHideDelaySeconds"] = true,
	["nameplatePersonalShowAlways"] = true,
	["nameplatePersonalShowInCombat"] = true,
	["nameplatePersonalShowWithTarget"] = true,
	["nameplateResourceOnTarget"] = true,
	["nameplateSelectedAlpha"] = true,
	["nameplateSelectedScale"] = true,
	["nameplateSelfAlpha"] = true,
	["nameplateSelfBottomInset"] = true,
	["nameplateSelfScale"] = true,
	["nameplateSelfTopInset"] = true,
	["nameplateShowAll"] = true,
	["nameplateShowEnemies"] = true,
	["nameplateShowEnemyGuardians"] = true,
	["nameplateShowEnemyMinions"] = true,
	["nameplateShowEnemyMinus"] = true,
	["nameplateShowEnemyPets"] = true,
	["nameplateShowEnemyTotems"] = true,
	["nameplateShowFriendlyGuardians"] = true,
	["nameplateShowFriendlyMinions"] = true,
	["nameplateShowFriendlyNPCs"] = true,
	["nameplateShowFriendlyPets"] = true,
	["nameplateShowFriendlyTotems"] = true,
	["nameplateShowFriends"] = true,
	["nameplateShowSelf"] = true,
	["nameplateTargetBehindMaxDistance"] = true,
	["NamePlateVerticalScale"] = true,
	["showArenaEnemyFrames"] = true,
	["showArenaEnemyPets"] = true,
	["showPartyPets"] = true,
	["showTargetOfTarget"] = true,
	["splashScreenBoost"] = true,
	["splashScreenNormal"] = true,
	["targetOfTargetMode"] = true,
	["uiScale"] = true,
	["uiScaleMultiplier"] = true,
	["UnitNameGuildTitle"] = true,
	["useCompactPartyFrames"] = true,
	["useUiScale"] = true,
}

addon.hiddenOptions = {
	-- Names
	["UnitNameOwn"] = { prettyName = UNIT_NAME_OWN, description = OPTION_TOOLTIP_UNIT_NAME_OWN, type = "boolean" },
	["UnitNameNPC"] = { prettyName = UNIT_NAME_NPC, description = OPTION_TOOLTIP_UNIT_NAME_NPC, type = "boolean" },
	["UnitNameNonCombatCreatureName"] = { prettyName = UNIT_NAME_NONCOMBAT_CREATURE, description = OPTION_TOOLTIP_UNIT_NAME_NONCOMBAT_CREATURE, type = "boolean" },
	["UnitNamePlayerGuild"] = { prettyName = UNIT_NAME_GUILD, description = OPTION_TOOLTIP_UNIT_NAME_GUILD, type = "boolean" },
	["UnitNameGuildTitle"] = { prettyName = UNIT_NAME_GUILD_TITLE, description = OPTION_TOOLTIP_UNIT_NAME_GUILD_TITLE , type = "boolean" },
	["UnitNamePlayerPVPTitle"] = { prettyName = UNIT_NAME_PLAYER_TITLE, description = OPTION_TOOLTIP_UNIT_NAME_PLAYER_TITLE, type = "boolean" },
	["UnitNameFriendlyPlayerName"] = { prettyName = UNIT_NAME_FRIENDLY, description = OPTION_TOOLTIP_UNIT_NAME_FRIENDLY, type = "boolean" },
	["UnitNameFriendlyPetName"] = { prettyName = UNIT_NAME_FRIENDLY_PETS, description = OPTION_TOOLTIP_UNIT_NAME_FRIENDLY_PETS, type = "boolean" },
	["UnitNameFriendlyGuardianName"] = { prettyName = UNIT_NAME_FRIENDLY_GUARDIANS, description = OPTION_TOOLTIP_UNIT_NAME_FRIENDLY_GUARDIANS, type = "boolean" },
	["UnitNameFriendlyTotemName"] = { prettyName = UNIT_NAME_FRIENDLY_TOTEMS, description = OPTION_TOOLTIP_UNIT_NAME_FRIENDLY_TOTEMS, type = "boolean" },
	["UnitNameFriendlyMinionName"] = { prettyName = UNIT_NAME_FRIENDLY_MINIONS, description = _T"", type = "boolean" },
	["UnitNameEnemyPlayerName"] = { prettyName = UNIT_NAME_ENEMY, description = OPTION_TOOLTIP_UNIT_NAME_ENEMY, type = "boolean" },
	["UnitNameEnemyPetName"] = { prettyName = UNIT_NAME_ENEMY_PETS, description = OPTION_TOOLTIP_UNIT_NAME_ENEMY_PETS, type = "boolean" },
	["UnitNameEnemyGuardianName"] = { prettyName = UNIT_NAME_ENEMY_GUARDIANS, description = OPTION_TOOLTIP_UNIT_NAME_ENEMY_GUARDIANS, type = "boolean" },
	["UnitNameEnemyTotemName"] = { prettyName = UNIT_NAME_ENEMY_TOTEMS, description = OPTION_TOOLTIP_UNIT_NAME_ENEMY_TOTEMS, type = "boolean" },
	["UnitNameEnemyMinionName"] = { prettyName = UNIT_NAME_ENEMY_MINIONS, description = _T"", type = "boolean" },
	["UnitNameForceHideMinus"] = { prettyName = UNIT_NAME_HIDE_MINUS, description = OPTION_TOOLTIP_UNIT_NAME_HIDE_MINUS, type = "boolean" },
	["UnitNameFriendlySpecialNPCName"] = { prettyName = NPC_NAMES_DROPDOWN_TRACKED, description = NPC_NAMES_DROPDOWN_TRACKED_TOOLTIP, type = "boolean" },
	["UnitNameHostleNPC"] = { prettyName = _T"Hostile NPCs", description = _T"Display names for hostile NPCs", type = "boolean" },
	["UnitNameInteractiveNPC"] = { prettyName = _T"Interactive NPCs", description = _T"Display names for interactive NPCs", type = "boolean" },
	-- Nameplates
	["nameplateShowFriends"] = { prettyName = UNIT_NAMEPLATES_SHOW_FRIENDS, description = OPTION_TOOLTIP_UNIT_NAMEPLATES_SHOW_FRIENDS, type = "boolean" },
	["nameplateShowFriendlyPets"] = { prettyName = UNIT_NAMEPLATES_SHOW_FRIENDLY_PETS, description = OPTION_TOOLTIP_UNIT_NAMEPLATES_SHOW_FRIENDLY_PETS, type = "boolean" },
	["nameplateShowFriendlyGuardians"] = { prettyName = UNIT_NAMEPLATES_SHOW_FRIENDLY_GUARDIANS, description = OPTION_TOOLTIP_UNIT_NAMEPLATES_SHOW_FRIENDLY_GUARDIANS, type = "boolean" },
	["nameplateShowFriendlyTotems"] = { prettyName = UNIT_NAMEPLATES_SHOW_FRIENDLY_TOTEMS, description = OPTION_TOOLTIP_UNIT_NAMEPLATES_SHOW_FRIENDLY_TOTEMS, type = "boolean" },
	["nameplateShowFriendlyNPCs"] = { prettyName = _T"Friendly NPCs", description = _T"Always show friendly NPC's nameplates", type = "boolean" },
	["nameplateShowEnemies"] = { prettyName = UNIT_NAMEPLATES_SHOW_ENEMIES, description = OPTION_TOOLTIP_UNIT_NAMEPLATES_SHOW_ENEMIES, type = "boolean" },
	["nameplateShowEnemyPets"] = { prettyName = UNIT_NAMEPLATES_SHOW_ENEMY_PETS, description = OPTION_TOOLTIP_UNIT_NAMEPLATES_SHOW_ENEMY_PETS, type = "boolean" },
	["nameplateShowEnemyGuardians"] = { prettyName = UNIT_NAMEPLATES_SHOW_ENEMY_GUARDIANS, description = OPTION_TOOLTIP_UNIT_NAMEPLATES_SHOW_ENEMY_GUARDIANS, type = "boolean" },
	["nameplateShowEnemyTotems"] = { prettyName = UNIT_NAMEPLATES_SHOW_ENEMY_TOTEMS, description = OPTION_TOOLTIP_UNIT_NAMEPLATES_SHOW_ENEMY_TOTEMS, type = "boolean" },
	["nameplateShowEnemyMinus"] = { prettyName = UNIT_NAMEPLATES_SHOW_ENEMY_MINUS, description = OPTION_TOOLTIP_UNIT_NAMEPLATES_SHOW_ENEMY_MINUS, type = "boolean" },
	["nameplateOtherAtBase"] = { prettyName = _T"Nameplate at Base", description = _T"Position other nameplates at the base, rather than overhead. 2=under unit, 0=over unit", type = "boolean" },
	["nameplateOverlapH"] = { prettyName = _T"Nameplate Overlap (Horizontal)", description = _T"Percentage amount for horizontal overlap of nameplates", type = "number" },
	["nameplateOverlapV"] = { prettyName = _T"Nameplate Overlap (Vertical)", description = _T"Percentage amount for vertical overlap of nameplates", type = "number" },
	["nameplateMaxDistance"] = { prettyName = _T"Nameplate Distance", description = _T"The max distance to show nameplates.", type = "number" },
	["nameplateTargetBehindMaxDistance"] = { prettyName = _T"Nameplate Target Behind Distance", description = _T"The max distance to show the target nameplate when the target is behind the camera.", type = "number" },
	["nameplateGlobalScale"] = { prettyName = _T"Nameplate Global Scale", description = _T"Applies global scaling to non-self nameplates, this is applied AFTER selected, min, and max scale.", type = "number" },
	["nameplateMinScale"] = { prettyName = _T"Nameplate Min Scale", description = _T"The minimum scale of nameplates.", type = "number" },
	["nameplateMaxScale"] = { prettyName = _T"Nameplate Max Scale", description = _T"The max scale of nameplates.", type = "number" },
	["nameplateLargerScale"] = { prettyName = _T"Nameplate Larger Scale", description = _T"An additional scale modifier for important monsters.", type = "number" },
	["nameplateMinScaleDistance"] = { prettyName = _T"Nameplate Min Scale Distance", description = _T"The distance from the max distance that nameplates will reach their minimum scale.", type = "number" },
	["nameplateMaxScaleDistance"] = { prettyName = _T"Nameplate Max Scale Distance", description = _T"The distance from the camera that nameplates will reach their maximum scale", type = "number" },
	["nameplateMinAlpha"] = { prettyName = _T"Nameplate Min Alpha", description = _T"The minimum alpha of nameplates.", type = "number" },
	["nameplateMaxAlpha"] = { prettyName = _T"Nameplate Max Alpha", description = _T"The max alpha of nameplates.", type = "number" },
	["nameplateMinAlphaDistance"] = { prettyName = _T"Nameplate Min Alpha Distance", description = _T"The distance from the max distance that nameplates will reach their minimum alpha.", type = "number" },
	["nameplateMaxAlphaDistance"] = { prettyName = _T"Nameplate Max Alpha Distance", description = _T"The distance from the camera that nameplates will reach their maximum alpha.", type = "number" },
	["nameplateSelectedScale"] = { prettyName = _T"Nameplate Selected Scale", description = _T"The scale of the selected nameplate.", type = "number" },
	["nameplateSelectedAlpha"] = { prettyName = _T"Nameplate Selected Alpha", description = _T"The alpha of the selected nameplate.", type = "number" },
	["nameplateSelfScale"] = { prettyName = _T"Nameplate Self Scale", description = _T"The scale of the self nameplate.", type = "number" },
	["nameplateSelfAlpha"] = { prettyName = _T"Nameplate Self Alpha", description = _T"The alpha of the self nameplate.", type = "number" },
	["nameplateSelfBottomInset"] = { prettyName = _T"Nameplate Self Bottom Inset", description = _T"The inset from the bottom (in screen percent) that the self nameplate is clamped to.", type = "number" },
	["nameplateSelfTopInset"] = { prettyName = _T"Nameplate Self Top Inset", description = _T"The inset from the top (in screen percent) that the self nameplate is clamped to.", type = "number" },
	["nameplateOtherBottomInset"] = { prettyName = _T"Nameplate Other Bottom Inset", description = _T"The inset from the bottom (in screen percent) that the non-self nameplates are clamped to.", type = "number" },
	["nameplateOtherTopInset"] = { prettyName = _T"Nameplate Other Top Inset", description = _T"The inset from the top (in screen percent) that the non-self nameplates are clamped to.", type = "number" },
	["nameplateLargeBottomInset"] = { prettyName = _T"Nameplate Large Bottom Inset", description = _T"The inset from the bottom (in screen percent) that large nameplates are clamped to.", type = "number" },
	["nameplateLargeTopInset"] = { prettyName = _T"Nameplate Large Top Inset", description = _T"The inset from the top (in screen percent) that large nameplates are clamped to.", type = "number" },
	["nameplateClassResourceTopInset"] = { prettyName = _T"Nameplate Class Resource Top Inset", description = _T"The inset from the top (in screen percent) that nameplates are clamped to when class resources are being displayed on them.", type = "number" },
	["NamePlateHorizontalScale"] = { prettyName = _T"Nameplate Horizontal Scale", description = _T"Applied to horizontal size of all nameplates.", type = "number" },
	["NamePlateVerticalScale"] = { prettyName = _T"Nameplate Vertical Scale", description = _T"Applied to vertical size of all nameplates.", type = "number" },
	["nameplateResourceOnTarget"] = { prettyName = _T"Nameplate Resource On Target", description = _T"Nameplate class resource overlay mode. 0=self, 1=target", type = "number" },
	["nameplateShowSelf"] = { prettyName = _T"Show Nameplate Resource Bar", description = _T"Display class resource bar. 0=off 1=on", type = "number" },
	["nameplateShowAll"] = { prettyName = _T"Always Show Nameplates", description = _T"Show nameplates at all times.", type = "number" },
	["nameplateMotion"] = { prettyName = _T"Nameplate Motion Type", description = _T"0 = Overlapping - 1 = Stacking", type = "number" },
	["namePlateFriendlySize"] = { prettyName = _T"", description = _T"", type = "number" },
	["namePlateEnemySize"] = { prettyName = _T"", description = _T"", type = "number" },
	["namePlateSelfClickThrough"] = { prettyName = _T"", description = _T"", type = "number" },
	["namePlateFriendlyClickThrough"] = { prettyName = _T"", description = _T"", type = "number" },
	["namePlateEnemyClickThrough"] = { prettyName = _T"", description = _T"", type = "number" },
	["nameplatePersonalShowAlways"] = { prettyName = _T"", description = _T"Always show personal nameplate", type = "boolean" },
	["nameplatePersonalShowInCombat"] = { prettyName = _T"", description = _T"Always show personal nameplate while in combat", type = "boolean" },
	["nameplatePersonalShowWithTarget"] = { prettyName = _T"", description = _T"Always show personal nameplate with a hostile target", type = "boolean" },
	["nameplatePersonalHideDelaySeconds"] = { prettyName = _T"", description = _T"The delay to wait before hiding the personal nameplate", type = "boolean" },
	["ShowNamePlateLoseAggroFlash"] = { prettyName = nil, description = _T"When enabled, if you are a tank role and lose aggro, the nameplate with briefly flash.", type = "boolean" },
	["ShowClassColorInNameplate"] = { prettyName = SHOW_CLASS_COLOR_IN_V_KEY, description = OPTION_TOOLTIP_SHOW_CLASS_COLOR_IN_V_KEY, type = "boolean" },
	["ShowClassColorInFriendlyNameplate"] = { prettyName = _T"Class color friendly nameplates", description = _T"Class color for friendly nameplates", type = "boolean" },
	
	["nameplateTargetRadialPosition"] = { prettyName = nil, description = _T"When target is off screen, position its nameplate radially around sides and bottom", type = "number"},
	["nameplateOccludedAlphaMult"] = { prettyName = nil, description = _T"Alpha multiplier of nameplates for occluded targets", type = "number"},


	["reverseCleanupBags"] = { prettyName = REVERSE_CLEAN_UP_BAGS_TEXT, description = OPTION_TOOLTIP_REVERSE_CLEAN_UP_BAGS, type = "boolean" },
	["lootLeftmostBag"] = { prettyName = REVERSE_NEW_LOOT_TEXT, description = OPTION_TOOLTIP_REVERSE_NEW_LOOT, type = "boolean" },
	["stopAutoAttackOnTargetChange"] = { prettyName = STOP_AUTO_ATTACK, description = OPTION_TOOLTIP_STOP_AUTO_ATTACK, type = "boolean" },
	["assistAttack"] = { prettyName = ASSIST_ATTACK, description = OPTION_TOOLTIP_ASSIST_ATTACK, type = "boolean" },
	["autoSelfCast"] = { prettyName = AUTO_SELF_CAST_TEXT, description = OPTION_TOOLTIP_SELF_CAST_TEXT, type = "boolean" },
	["ActionButtonUseKeyDown"] = { prettyName = ACTION_BUTTON_USE_KEY_DOWN, description = OPTION_TOOLTIP_ACTION_BUTTON_USE_KEY_DOWN, type = "boolean" },
	["mapFade"] = { prettyName = MAP_FADE_TEXT, description = OPTION_TOOLTIP_MAP_FADE, type = "boolean" },
	["trackQuestSorting"] = { type = "table", options = {"proximity", "top" } },
	["removeChatDelay"] = { prettyName = REMOVE_CHAT_DELAY_TEXT, description = OPTION_TOOLTIP_REMOVE_CHAT_DELAY_TEXT, type = "boolean" },
	["secureAbilityToggle"] = { prettyName = SECURE_ABILITY_TOGGLE, description = OPTION_TOOLTIP_SECURE_ABILITY_TOGGLE, type = "boolean" },
	["scriptErrors"] = { prettyName = SHOW_LUA_ERRORS, description = OPTION_TOOLTIP_SHOW_LUA_ERRORS, type = "boolean" },
	["lootUnderMouse"] = { prettyName = LOOT_UNDER_MOUSE_TEXT, description = OPTION_TOOLTIP_LOOT_UNDER_MOUSE_TEXT, type = "boolean" },
	["ShowQuestUnitCircles"] = { prettyName = _T"Quest Unit Circles", description = _T"Determines if units related to a quest display an indicator on the ground", type = "boolean" },
	["autoLootDefault"] = { prettyName = AUTO_LOOT_DEFAULT_TEXT, description = OPTION_TOOLTIP_AUTO_LOOT_DEFAULT, type = "boolean" },
	["threatShowNumeric"] = { prettyName = SHOW_NUMERIC_THREAT, description = OPTION_TOOLTIP_SHOW_NUMERIC_THREAT, type = "boolean" },
	["showLootSpam"] = { prettyName = SHOW_LOOT_SPAM, description = OPTION_TOOLTIP_SHOW_LOOT_SPAM, type = "boolean" },
	["advancedWatchFrame"] = { prettyName = ADVANCED_OBJECTIVES_TEXT, description = OPTION_TOOLTIP_ADVANCED_OBJECTIVES_TEXT, type = "" },
	["watchFrameIgnoreCursor"] = { prettyName = OBJECTIVES_IGNORE_CURSOR_TEXT, description = OPTION_TOOLTIP_OBJECTIVES_IGNORE_CURSOR, type = "boolean" },
	["guildMemberNotify"] = { prettyName = GUILDMEMBER_ALERT, description = OPTION_TOOLTIP_GUILDMEMBER_ALERT, type = "boolean" },
	["showArenaEnemyFrames"] = { prettyName = SHOW_ARENA_ENEMY_FRAMES_TEXT, description = OPTION_TOOLTIP_SHOW_ARENA_ENEMY_FRAMES, type = "boolean" },
	["autoClearAFK"] = { prettyName = nil, description = OPTION_TOOLTIP_CLEAR_AFK, type = "boolean" },
	["colorblindWeaknessFactor"] = { prettyName = nil, description = OPTION_TOOLTIP_ADJUST_COLORBLIND_STRENGTH, type = "boolean" },
	["autoLootDefault"] = { prettyName = nil, description = OPTION_TOOLTIP_AUTO_LOOT_DEFAULT, type = "boolean" },
	["autoLootRate"] = { prettyName = _T"Auto Loot Rate", description = _T"Rate in milliseconds to tick auto loot", type = "number" },
	["ChatAmbienceVolume"] = { prettyName = nil, description = OPTION_TOOLTIP_, type = "boolean" },
	["threatShowNumeric"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_NUMERIC_THREAT, type = "boolean" },
	["rightActionBar"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_MULTIBAR3, type = "boolean" },
	["emphasizeMySpellEffects"] = { prettyName = nil, description = OPTION_TOOLTIP_EMPHASIZE_MY_SPELLS, type = "boolean" },
	["chatBubblesParty"] = { prettyName = nil, description = OPTION_TOOLTIP_PARTY_CHAT_BUBBLES, type = "boolean" },
	["enableTwitter"] = { prettyName = nil, description = OPTION_TOOLTIP_SOCIAL_ENABLE_TWITTER_FUNCTIONALITY, type = "boolean" },
	["threatPlaySounds"] = { prettyName = nil, description = OPTION_TOOLTIP_PLAY_AGGRO_SOUNDS, type = "boolean" },
	-- Toasts mmhhh...Toast.
	["showToastOnline"] = { prettyName = SHOW_TOAST_ONLINE_TEXT, description = OPTION_TOOLTIP_SHOW_TOAST_ONLINE, type = "boolean" },
	["showToastOffline"] = { prettyName = SHOW_TOAST_OFFLINE_TEXT, description = OPTION_TOOLTIP_SHOW_TOAST_OFFLINE, type = "boolean" },
	["showToastBroadcast"] = { prettyName = SHOW_TOAST_BROADCAST_TEXT, description = OPTION_TOOLTIP_SHOW_TOAST_BROADCAST, type = "boolean" },
	["showToastFriendRequest"] = { prettyName = SHOW_TOAST_FRIEND_REQUEST_TEXT, description = OPTION_TOOLTIP_SHOW_TOAST_FRIEND_REQUEST, type = "boolean" },
	["showToastConversation"] = { prettyName = SHOW_TOAST_CONVERSATION_TEXT, description = OPTION_TOOLTIP_SHOW_TOAST_CONVERSATION, type = "boolean" },
	["showToastWindow"] = { prettyName = SHOW_TOAST_WINDOW_TEXT, description = OPTION_TOOLTIP_SHOW_TOAST_WINDOW, type = "boolean" },
	["toastDuration"] = { prettyName = nil, description = OPTION_TOOLTIP_TOAST_DURATION, type = "number" },

	["enableMouseSpeed"] = { prettyName = ENABLE_MOUSE_SPEED, description = OPTION_TOOLTIP_ENABLE_MOUSE_SPEED, type = "boolean" },
	["mouseInvertPitch"] = { prettyName = INVERT_MOUSE, description = OPTION_TOOLTIP_INVERT_MOUSE, type = "boolean" },
	["enableWoWMouse"] = { prettyName = WOW_MOUSE, description = OPTION_TOOLTIP_WOW_MOUSE, type = "boolean" },
	["autointeract"] = { prettyName = CLICK_TO_MOVE, description = OPTION_TOOLTIP_CLICK_TO_MOVE, type = "boolean" },
	["mouseSpeed"] = { prettyName = MOUSE_SENSITIVITY, description = OPTION_TOOLTIP_MOUSE_SENSITIVITY, type = "number" },

	["wholeChatWindowClickable"] = { prettyName = nil, description = OPTION_TOOLTIP_CHAT_WHOLE_WINDOW_CLICKABLE, type = "boolean" },
	["useEnglishAudio"] = { prettyName = nil, description = OPTION_TOOLTIP_USE_ENGLISH_AUDIO, type = "boolean" },
	["ChatSoundVolume"] = { prettyName = nil, description = OPTION_TOOLTIP_, type = "number" },
	--["reducedLagTolerance"] = { prettyName = _T"Custom Lag Tolerance", description = OPTION_TOOLTIP_REDUCED_LAG_TOLERANCE, type = "boolean" },
	["EnableMicrophone"] = { prettyName = nil, description = OPTION_TOOLTIP_ENABLE_MICROPHONE, type = "boolean" },
	["autoOpenLootHistory"] = { prettyName = nil, description = OPTION_TOOLTIP_AUTO_OPEN_LOOT_HISTORY, type = "boolean" },
	["showVKeyCastbarOnlyOnTarget"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_TARGET_CASTBAR_IN_V_KEY_ONLY_ON_TARGET, type = "boolean" },
	["displaySpellActivationOverlays"] = { prettyName = nil, description = OPTION_TOOLTIP_DISPLAY_SPELL_ALERTS, type = "boolean" },
	["hdPlayerModels"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_HD_MODELS, type = "boolean" },
	["autoLootKey"] = { prettyName = nil, description = OPTION_TOOLTIP_AUTO_LOOT_KEY, type = "boolean" }, -- TODO TYPE
	["SpellQueueWindow"] = { prettyName = LAG_TOLERANCE, description = _T"Determines how far ahead of the \'end of a spell\' start-recovery spell system can be, before allowing spell request to be sent to the server. Ie this controls the built-in lag for the ability queuing system. Ideally, you\'ll want to set this to your in-game latency.", type = "number" },
	["advancedCombatLogging"] = { prettyName = nil, description = OPTION_TOOLTIP_ADVANCED_COMBAT_LOGGING, type = "boolean" },
	["disableServerNagle"] = { prettyName = nil, description = OPTION_TOOLTIP_OPTIMIZE_NETWORK_SPEED, type = "boolean" },
	-- Camera
	["cameraYawSmoothSpeed"] = { prettyName = nil, description = OPTION_TOOLTIP_AUTO_FOLLOW_SPEED, type = "number" },
	["cameraWaterCollision"] = { prettyName = nil, description = OPTION_TOOLTIP_WATER_COLLISION, type = "boolean" },
	["cameraBobbing"] = { prettyName = nil, description = OPTION_TOOLTIP_HEAD_BOB, type = "boolean" },
	["cameraPivot"] = { prettyName = nil, description = OPTION_TOOLTIP_SMART_PIVOT, type = "boolean" },
	["cameraDistanceMaxZoomFactor"] = { prettyName = MAX_FOLLOW_DIST, description = OPTION_TOOLTIP_MAX_FOLLOW_DIST, type = "number" },
	["cameraYawMoveSpeed"] = { prettyName = MOUSE_LOOK_SPEED, description = OPTION_TOOLTIP_MOUSE_LOOK_SPEED, type = "number" },
	["cameraTerrainTilt"] = { prettyName = nil, description = OPTION_TOOLTIP_FOLLOW_TERRAIN, type = "boolean" },
	["cameraHeadMovementStrength"] = { prettyName = nil, description = nil, type = "number" },
	["cameraHeadMovementWhileStanding"] = { prettyName = nil, description = nil, type = "number" },
	["cameraHeadMovementRange"] = { prettyName = nil, description = nil, type = "number" },
	["cameraHeadMovementSmoothRate"] = { prettyName = nil, description = nil, type = "number" },
	["cameraDynamicPitch"] = { prettyName = nil, description = nil, type = "number" },
	-- ["cameraDynamicPitchBaseFovPad"] = { prettyName = nil, description = nil, type = "number" },
	["cameraDynamicPitchBaseFovPadFlying"] = { prettyName = nil, description = nil, type = "number" },
	["cameraDynamicPitchSmartPivotCutoffDist"] = { prettyName = nil, description = nil, type = "number" },
	["cameraOverShoulder"] = { prettyName = nil, description = nil, type = "number" },
	["cameraLockedTargetFocusing"] = { prettyName = nil, description = nil, type = "number" },
	["cameraDistanceMoveSpeed"] = { prettyName = nil, description = nil, type = "number" },
	["cameraPitchMoveSpeed"] = { prettyName = nil, description = nil, type = "number" },
	["cameraBobbingSmoothSpeed"] = { prettyName = nil, description = nil, type = "number" },
	["cameraFoVSmoothSpeed"] = { prettyName = nil, description = nil, type = "number" },
	["cameraDistanceSmoothSpeed"] = { prettyName = nil, description = nil, type = "number" },
	["cameraGroundSmoothSpeed"] = { prettyName = nil, description = nil, type = "number" },
	["cameraHeightSmoothSpeed"] = { prettyName = nil, description = nil, type = "number" },
	["cameraPitchSmoothSpeed"] = { prettyName = nil, description = nil, type = "number" },
	["cameraTargetSmoothSpeed"] = { prettyName = nil, description = nil, type = "number" },
	-- ["cameraFlyingMountHeightSmoothSpeed"] = { prettyName = nil, description = nil, type = "number" },
	["cameraViewBlendStyle"] = { prettyName = nil, description = nil, type = "number" },
	["camerasmooth"] = { prettyName = nil, description = nil, type = "number" },
	["cameraSmoothPitch"] = { prettyName = nil, description = nil, type = "number" },
	["cameraSmoothYaw"] = { prettyName = nil, description = nil, type = "number" },
	["cameraSmoothStyle"] = { prettyName = nil, description = nil, type = "number" },
	["cameraSmoothTrackingStyle"] = { prettyName = nil, description = nil, type = "number" },

	["chatBubbles"] = { prettyName = nil, description = OPTION_TOOLTIP_CHAT_BUBBLES, type = "boolean" },
	["autoDismountFlying"] = { prettyName = nil, description = OPTION_TOOLTIP_AUTO_DISMOUNT_FLYING, type = "boolean" },
	["bottomRightActionBar"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_MULTIBAR2, type = "boolean" },
	["showPartyBackground"] = { prettyName = SHOW_PARTY_BACKGROUND_TEXT, description = OPTION_TOOLTIP_SHOW_PARTY_BACKGROUND, type = "boolean" },
	["showPartyPets"] = { prettyName = SHOW_PARTY_PETS_TEXT, description = OPTION_TOOLTIP_SHOW_PARTY_PETS, type = "boolean" },
	["showArenaEnemyFrames"] = { prettyName = SHOW_ARENA_ENEMY_FRAMES_TEXT, description = OPTION_TOOLTIP_SHOW_ARENA_ENEMY_FRAMES, type = "boolean" },
	["showArenaEnemyCastbar"] = { prettyName = SHOW_ARENA_ENEMY_CASTBAR_TEXT, description = OPTION_TOOLTIP_SHOW_ARENA_ENEMY_CASTBAR, type = "boolean" },
	["showArenaEnemyPets"] = { prettyName = SHOW_ARENA_ENEMY_PETS_TEXT, description = OPTION_TOOLTIP_SHOW_ARENA_ENEMY_PETS, type = "boolean" },
	["fullSizeFocusFrame"] = { prettyName = FULL_SIZE_FOCUS_FRAME_TEXT, description = OPTION_TOOLTIP_FULL_SIZE_FOCUS_FRAME, type = "boolean" },
	["spamFilter"] = { prettyName = nil, description = OPTION_TOOLTIP_SPAM_FILTER, type = "boolean" },
	["profanityFilter"] = { prettyName = nil, description = OPTION_TOOLTIP_PROFANITY_FILTER, type = "boolean" },
	["EnableVoiceChat"] = { prettyName = nil, description = OPTION_TOOLTIP_ENABLE_VOICECHAT, type = "boolean" },
	["rightTwoActionBar"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_MULTIBAR4, type = "boolean" },
	["rotateMinimap"] = { prettyName = nil, description = OPTION_TOOLTIP_ROTATE_MINIMAP, type = "boolean" },
	["blockTrades"] = { prettyName = nil, description = OPTION_TOOLTIP_BLOCK_TRADES, type = "boolean" },
	["movieSubtitle"] = { prettyName = nil, description = OPTION_TOOLTIP_CINEMATIC_SUBTITLES, type = "boolean" },
	["displayFreeBagSlots"] = { prettyName = nil, description = OPTION_TOOLTIP_DISPLAY_FREE_BAG_SLOTS, type = "boolean" },
	["lockActionBars"] = { prettyName = nil, description = OPTION_TOOLTIP_LOCK_ACTIONBAR, type = "boolean" },
	["screenEdgeFlash"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_FULLSCREEN_STATUS, type = "boolean" },
	["showVKeyCastbar"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_TARGET_CASTBAR_IN_V_KEY, type = "boolean" },
	["chatMouseScroll"] = { prettyName = CHAT_MOUSE_WHEEL_SCROLL, description = OPTION_TOOLTIP_CHAT_MOUSE_WHEEL_SCROLL, type = "boolean" },
	["InboundChatVolume"] = { prettyName = nil, description = OPTION_TOOLTIP_VOICE_OUTPUT_VOLUME, type = "number" },
	["spellActivationOverlayOpacity"] = { prettyName = nil, description = OPTION_TOOLTIP_SPELL_ALERT_OPACITY, type = "number" },
	["PushToTalkSound"] = { prettyName = nil, description = OPTION_TOOLTIP_PUSHTOTALK_SOUND, type = "boolean" },
	["countdownForCooldowns"] = { prettyName = nil, description = OPTION_TOOLTIP_COUNTDOWN_FOR_COOLDOWNS, type = "boolean" },
	["VoiceActivationSensitivity"] = { prettyName = nil, description = OPTION_TOOLTIP_VOICE_ACTIVATION_SENSITIVITY, type = "number" },
	["alwaysShowActionBars"] = { prettyName = nil, description = OPTION_TOOLTIP_ALWAYS_SHOW_MULTIBARS, type = "boolean" },
	["OutboundChatVolume"] = { prettyName = nil, description = OPTION_TOOLTIP_VOICE_INPUT_VOLUME, type = "number" },
	["autoQuestWatch"] = { prettyName = nil, description = OPTION_TOOLTIP_AUTO_QUEST_WATCH, type = "boolean" },
	["SpellTooltip_DisplayAvgValues"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_POINTS_AS_AVG, type = "boolean" },
	["bottomLeftActionBar"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_MULTIBAR1, type = "boolean" },
	["showVKeyCastbarSpellName"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_TARGET_CASTBAR_IN_V_KEY_SPELL_NAME, type = "boolean" },
	["buffDurations"] = { prettyName = SHOW_BUFF_DURATION_TEXT, description = OPTION_TOOLTIP_SHOW_BUFF_DURATION, type = "boolean" },
	["showDispelDebuffs"] = { prettyName = SHOW_DISPELLABLE_DEBUFFS_TEXT, description = OPTION_TOOLTIP_SHOW_DISPELLABLE_DEBUFFS, type = "boolean" },
	["showCastableBuffs"] = { prettyName = SHOW_CASTABLE_BUFFS_TEXT, description = OPTION_TOOLTIP_SHOW_CASTABLE_BUFFS, type = "boolean" },
	["deselectOnClick"] = { prettyName = nil, description = OPTION_TOOLTIP_GAMEFIELD_DESELECT, type = "boolean" },
	["autoQuestProgress"] = { prettyName = nil, description = OPTION_TOOLTIP_AUTO_QUEST_PROGRESS, type = "boolean" },
	["UberTooltips"] = { prettyName = USE_UBERTOOLTIPS, description = OPTION_TOOLTIP_USE_UBERTOOLTIPS, type = "boolean" },
	-- Sound
	["Sound_EnableAllSound"] = { prettyName = ENABLE_SOUND, description = OPTION_TOOLTIP_ENABLE_SOUND, type = "boolean" },
	["Sound_EnableDSPEffects"] = { prettyName = ENABLE_DSP_EFFECTS, description = OPTION_TOOLTIP_ENABLE_DSP_EFFECTS, type = "boolean" },
	["Sound_SFXVolume"] = { prettyName = SOUND_VOLUME, description = OPTION_TOOLTIP_SOUND_VOLUME, type = "number" },
	["Sound_ZoneMusicNoDelay"] = { prettyName = ENABLE_MUSIC_LOOPING, description = OPTION_TOOLTIP_ENABLE_MUSIC_LOOPING, type = "boolean" },
	["Sound_EnableDialog"] = { prettyName = ENABLE_DIALOG, description = OPTION_TOOLTIP_ENABLE_DIALOG, type = "boolean" },
	["Sound_EnableSoundWhenGameIsInBG"] = { prettyName = ENABLE_BGSOUND, description = OPTION_TOOLTIP_ENABLE_BGSOUND, type = "boolean" },
	["Sound_EnableEmoteSounds"] = { prettyName = ENABLE_EMOTE_SOUNDS, description = OPTION_TOOLTIP_ENABLE_EMOTE_SOUNDS, type = "boolean" },
	["Sound_EnableAmbience"] = { prettyName = ENABLE_AMBIENCE, description = OPTION_TOOLTIP_ENABLE_AMBIENCE, type = "boolean" },
	["Sound_DialogVolume"] = { prettyName = DIALOG_VOLUME, description = OPTION_TOOLTIP_DIALOG_VOLUME, type = "number" },
	["Sound_EnablePetBattleMusic"] = { prettyName = ENABLE_PET_BATTLE_MUSIC, description = OPTION_TOOLTIP_ENABLE_PET_BATTLE_MUSIC, type = "boolean" },
	["Sound_MusicVolume"] = { prettyName = MUSIC_VOLUME, description = OPTION_TOOLTIP_MUSIC_VOLUME, type = "number" },
	["Sound_EnableReverb"] = { prettyName = ENABLE_REVERB, description = OPTION_TOOLTIP_ENABLE_REVERB, type = "boolean" },
	["Sound_MasterVolume"] = { prettyName = MASTER_VOLUME, description = OPTION_TOOLTIP_MASTER_VOLUME, type = "number" },
	["Sound_EnableMusic"] = { prettyName = ENABLE_MUSIC, description = OPTION_TOOLTIP_ENABLE_MUSIC, type = "boolean" },
	["Sound_AmbienceVolume"] = { prettyName = AMBIENCE_VOLUME, description = OPTION_TOOLTIP_AMBIENCE_VOLUME, type = "number" },
	["Sound_EnableErrorSpeech"] = { prettyName = ENABLE_ERROR_SPEECH, description = OPTION_TOOLTIP_ENABLE_ERROR_SPEECH, type = "boolean" },
	["Sound_EnableSFX"] = { prettyName = ENABLE_SOUNDFX, description = OPTION_TOOLTIP_ENABLE_SOUNDFX, type = "boolean" },
	["Sound_ListenerAtCharacter"] = { prettyName = ENABLE_SOUND_AT_CHARACTER, description = OPTION_TOOLTIP_ENABLE_SOUND_AT_CHARACTER, type = "boolean" },
	["Sound_EnablePetSounds"] = { prettyName = ENABLE_PET_SOUNDS, description = OPTION_TOOLTIP_ENABLE_PET_SOUNDS, type = "boolean" },
	["Sound_EnablePositionalLowPassFilter"] = { prettyName = ENABLE_SOFTWARE_HRTF, description = OPTION_TOOLTIP_ENABLE_SOFTWARE_HRTF, type = "boolean" },

	["showTargetOfTarget"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_TARGET_OF_TARGET, type = "boolean" },
	["guildMemberNotify"] = { prettyName = nil, description = OPTION_TOOLTIP_GUILDMEMBER_ALERT, type = "boolean" },
	["showTutorials"] = { prettyName = SHOW_TUTORIALS, description = OPTION_TOOLTIP_SHOW_TUTORIALS, type = "boolean" },
	["lossOfControl"] = { prettyName = nil, description = OPTION_TOOLTIP_LOSS_OF_CONTROL, type = "boolean" },
	["blockChannelInvites"] = { prettyName = nil, description = OPTION_TOOLTIP_BLOCK_CHAT_CHANNEL_INVITE, type = "boolean" },
	["showTargetCastbar"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_TARGET_CASTBAR, type = "boolean" },
	["enablePetBattleCombatText"] = { prettyName = nil, description = OPTION_TOOLTIP_SHOW_PETBATTLE_COMBAT, type = "boolean" },
	["colorblindMode"] = { prettyName = nil, description = OPTION_TOOLTIP_USE_COLORBLIND_MODE, type = "boolean" },
	["useIPv6"] = { prettyName = USEIPV6, description = OPTION_TOOLTIP_USEIPV6, type = "boolean" },
	["interactOnLeftClick"] = { prettyName = INTERACT_ON_LEFT_CLICK_TEXT, description = OPTION_TOOLTIP_INTERACT_ON_LEFT_CLICK, type = "boolean" },
	["enableMovePad"] = { prettyName = MOVE_PAD, description = OPTION_TOOLTIP_MOVE_PAD, type = "boolean" },
	["colorblindSimulator"] = { prettyName = nil, description = OPTION_TOOLTIP_COLORBLIND_FILTER, type = "boolean" },

	["noBuffDebuffFilterOnTarget"] = { prettyName = _T"No Debuff Filter on Target", description = _T"Do not filter buffs or debuffs at all on targets", type = "boolean" },
	["showHonorAsExperience"] = { prettyName = nil, description = _T"Show the honor bar as a regular experience bar in place of rep", type = "boolean" },
	-- Tab-Targetting
	["TargetNearestUseNew"] = { prettyName = nil, description = _T"Use 7.2 'nearest target' functionality", type = "boolean" },
	--["TargetPriorityAllowAnyOnScreen"] = { prettyName = nil, description = _T"If set, and no 100% correct target is available, allow selecting any valid in-range target (2 = also out-of-range)", type = "boolean" },
	["TargetPriorityCombatLock"] = { prettyName = nil, description = _T"1=Lock to in-combat targets when starting from an in-combat target. 2=Further restrict to in-combat with player.", type = "boolean" },
	["TargetPriorityCombatLockHighlight"] = { prettyName = nil, description = _T"1=Lock to in-combat targets when starting from an in-combat target. 2=Further restrict to in-combat with player. (while doing hold-to-target)", type = "boolean" },
	--["TargetPriorityHoldHighlightDelay"] = { prettyName = nil, description = _T"Delay in Milliseconds before priority target highlight starts when holding the button", type = "number" },
	--["TargetPriorityIncludeBehind"] = { prettyName = nil, description = _T"If set, include target's behind the player in priority target selection", type = "boolean" },
	["TargetPriorityPvp"] = { prettyName = nil, description = _T"When in pvp, give higher priority to players and important pvp targets (2 = all pvp targets, 3 = players only)", type = "boolean" },
	--["TargetPriorityPvpLock"] = { prettyName = nil, description = _T"Lock to important pvp targets when starting from a pvp target.", type = "boolean" },
	--["TargetPriorityPvpLockHighlight"] = { prettyName = nil, description = _T"Lock to players when starting from a player target in pvp. (while doing hold-to-target)", type = "boolean" },
	--["TargetPriorityValueBank"] = { prettyName = nil, description = _T"Selects the scoring values bank for calculating target priority order", type = "boolean" },
	["TargetPriorityCombatLockContextualRelaxation"] = { prettyName = nil, description = _T"1=Enables relaxation of combat lock based on context (eg. no in-combat target infront)", type = "number" },

	["unitClutter"] = { prettyName = nil, description = _T"Enables/Disables unit clutter", type = "boolean" },
	["unitClutterInstancesOnly"] = { prettyName = nil, description = _T"Whether or not to use unit clutter in instances only (0 or 1)", type = "boolean" },
	["unitClutterPlayerThreshold"] = { prettyName = nil, description = _T"The number of players that have to be nearby to trigger unit clutter", type = "boolean" },

	["comboPointLocation"] = { prettyName = nil, description = _T"Location of combo points in UI. 1=target, 2=self", type = "number" },
	["doNotFlashLowHealthWarning"] = { prettyName = nil, description = _T"Do not flash your screen red when you are low on health.", type = "boolean" },
	["findYourselfAnywhere"] = { prettyName = nil, description = _T"Always Highlight your character", type = "boolean" },
	["findYourselfAnywhereOnlyInCombat"] = { prettyName = nil, description = _T"Highlight your character only when in combat", type = "boolean" },
	["findYourselfInBG"] = { prettyName = nil, description = _T"Always Highlight your character in Battlegrounds", type = "boolean" },
	["findYourselfInBGOnlyInCombat"] = { prettyName = _T"Highlight your character in Battlegrounds only when in combat", description = _T"", type = "boolean" },
	["findYourselfInRaid"] = { prettyName = nil, description = _T"Always Highlight your character in Raids", type = "boolean" },
	["findYourselfInRaidOnlyInCombat"] = { prettyName = nil, description = _T"Highlight your character in Raids only when in combat", type = "boolean" },
	["findYourselfMode"] = { prettyName = nil, description = _T"Highlight you character. 0 = circle, 1 = circle & outline", type = "boolean" },
	["flashErrorMessageRepeats"] = { prettyName = nil, description = _T"Flashes the center screen red error text if the same message is fired.", type = "boolean" },
	-- Floating Combat Text
	["enableFloatingCombatText"] = { prettyName = SHOW_COMBAT_TEXT_TEXT, description = OPTION_TOOLTIP_SHOW_COMBAT_TEXT , type = "boolean" },
	["floatingCombatTextAllSpellMechanics"] = { prettyName = nil, description = _T"", type = "boolean" },
	["floatingCombatTextAuras"] = { prettyName = COMBAT_TEXT_SHOW_AURAS_TEXT, description = OPTION_TOOLTIP_COMBAT_TEXT_SHOW_AURAS , type = "boolean" },
	["floatingCombatTextCombatDamage"] = { prettyName = SHOW_DAMAGE_TEXT, description = OPTION_TOOLTIP_SHOW_DAMAGE, type = "boolean" },
	["floatingCombatTextCombatDamageAllAutos"] = { prettyName = nil, description = _T"Show all auto-attack numbers, rather than hiding non-event numbers", type = "boolean" },
	["floatingCombatTextCombatDamageDirectionalOffset"] = { prettyName = nil, description = _T"Amount to offset directional damage numbers when they start", type = "boolean" },
	["floatingCombatTextCombatDamageDirectionalScale"] = { prettyName = _T"Directional Scale", description = _T"Directional damage numbers movement scale (disabled = no directional numbers)", type = "boolean" },
	["floatingCombatTextCombatHealing"] = { prettyName = SHOW_COMBAT_HEALING, description = OPTION_TOOLTIP_SHOW_COMBAT_HEALING, type = "boolean" },
	["floatingCombatTextCombatHealingAbsorbSelf"] = { prettyName = SHOW_COMBAT_HEALING_ABSORB_SELF.." (Self)", description = OPTION_TOOLTIP_SHOW_COMBAT_HEALING_ABSORB_SELF, type = "boolean" },
	["floatingCombatTextCombatHealingAbsorbTarget"] = { prettyName = SHOW_COMBAT_HEALING_ABSORB_TARGET.." (Target)" , description = OPTION_TOOLTIP_SHOW_COMBAT_HEALING_ABSORB_TARGET, type = "boolean" },
	["floatingCombatTextCombatLogPeriodicSpells"] = { prettyName = LOG_PERIODIC_EFFECTS, description = OPTION_TOOLTIP_LOG_PERIODIC_EFFECTS, type = "boolean" },
	["floatingCombatTextCombatState"] = { prettyName = COMBAT_TEXT_SHOW_COMBAT_STATE_TEXT, description = OPTION_TOOLTIP_COMBAT_TEXT_SHOW_COMBAT_STATE, type = "boolean" },
	["floatingCombatTextComboPoints"] = { prettyName = COMBAT_TEXT_SHOW_COMBO_POINTS_TEXT, description = OPTION_TOOLTIP_COMBAT_TEXT_SHOW_COMBO_POINTS , type = "boolean" },
	["floatingCombatTextDamageReduction"] = { prettyName =COMBAT_TEXT_SHOW_RESISTANCES_TEXT, description = OPTION_TOOLTIP_COMBAT_TEXT_SHOW_RESISTANCES, type = "boolean" },
	["floatingCombatTextDodgeParryMiss"] = { prettyName = COMBAT_TEXT_SHOW_DODGE_PARRY_MISS_TEXT, description = OPTION_TOOLTIP_COMBAT_TEXT_SHOW_DODGE_PARRY_MISS, type = "boolean" },
	["floatingCombatTextEnergyGains"] = { prettyName = COMBAT_TEXT_SHOW_ENERGIZE_TEXT.." & "..COMBAT_TEXT_SHOW_COMBO_POINTS_TEXT, description = OPTION_TOOLTIP_COMBAT_TEXT_SHOW_ENERGIZE, type = "boolean" },
	["floatingCombatTextFloatMode"] = { prettyName = COMBAT_TEXT_FLOAT_MODE_LABEL, description = OPTION_TOOLTIP_COMBAT_TEXT_MODE, type = "number" },
	["floatingCombatTextFriendlyHealers"] = { prettyName = COMBAT_TEXT_SHOW_FRIENDLY_NAMES_TEXT, description = OPTION_TOOLTIP_COMBAT_TEXT_SHOW_FRIENDLY_NAMES, type = "boolean" },
	["floatingCombatTextHonorGains"] = { prettyName = COMBAT_TEXT_SHOW_HONOR_GAINED_TEXT, description = OPTION_TOOLTIP_COMBAT_TEXT_SHOW_HONOR_GAINED, type = "boolean" },
	["floatingCombatTextLowManaHealth"] = { prettyName = COMBAT_TEXT_SHOW_LOW_HEALTH_MANA_TEXT, description = OPTION_TOOLTIP_COMBAT_TEXT_SHOW_LOW_HEALTH_MANA, type = "boolean" },
	["floatingCombatTextPeriodicEnergyGains"] = { prettyName = COMBAT_TEXT_SHOW_PERIODIC_ENERGIZE_TEXT, description = OPTION_TOOLTIP_COMBAT_TEXT_SHOW_PERIODIC_ENERGIZE, type = "boolean" },
	["floatingCombatTextPetMeleeDamage"] = { prettyName = SHOW_PET_MELEE_DAMAGE, description = OPTION_TOOLTIP_SHOW_PET_MELEE_DAMAGE, type = "boolean" },
	["floatingCombatTextPetSpellDamage"] = { prettyName = SHOW_PET_SPELL_DAMAGE, description = _T"Display pet spell damage in the world", type = "boolean" },
	["floatingCombatTextReactives"] = { prettyName = COMBAT_TEXT_SHOW_REACTIVES_TEXT, description = OPTION_TOOLTIP_COMBAT_TEXT_SHOW_REACTIVES, type = "boolean" },
	["floatingCombatTextRepChanges"] = { prettyName = COMBAT_TEXT_SHOW_REPUTATION_TEXT, description = OPTION_TOOLTIP_COMBAT_TEXT_SHOW_REPUTATION, type = "boolean" },
	["floatingCombatTextSpellMechanics"] = { prettyName = SHOW_TARGET_EFFECTS, description = OPTION_TOOLTIP_SHOW_TARGET_EFFECTS, type = "boolean" },
	["floatingCombatTextSpellMechanicsOther"] = { prettyName = SHOW_OTHER_TARGET_EFFECTS, description = OPTION_TOOLTIP_SHOW_OTHER_TARGET_EFFECTS, type = "boolean" },
	-- Status Text
	["statusText"] = { prettyName = STATUS_TEXT, description = _T"Whether the status bars show numeric health/mana values", type = "boolean"},
	["statusTextDisplay"] = { prettyName = STATUS_TEXT, description = OPTION_TOOLTIP_STATUS_TEXT_DISPLAY, type = "boolean"},
	["playerStatusText"] = { prettyName = STATUS_TEXT_PLAYER, description = OPTION_TOOLTIP_STATUS_TEXT_PLAYER , type = "boolean"}, -- removed
	["petStatusText"] = { prettyName = STATUS_TEXT_PET, description = OPTION_TOOLTIP_STATUS_TEXT_PET, type = "boolean"}, -- removed
	["partyStatusText"] = { prettyName = STATUS_TEXT_PARTY, description = OPTION_TOOLTIP_STATUS_TEXT_PARTY, type = "boolean"}, -- removed
	["targetStatusText"] = { prettyName = STATUS_TEXT_TARGET, description = OPTION_TOOLTIP_STATUS_TEXT_TARGET, type = "boolean"}, -- removed
	["alternateResourceText"] = { prettyName = ALTERNATE_RESOURCE_TEXT, description = OPTION_TOOLTIP_ALTERNATE_RESOURCE, type = "boolean"}, -- removed
	["xpBarText"] = { prettyName = XP_BAR_TEXT, description = OPTION_TOOLTIP_XP_BAR, type = "boolean" },

	["violenceLevel"] = { prettyName = _T"Violence Level", description = _T"Sets the violence level of the game", type = "number" },
	["ffxGlow"] = { prettyName = _T"FFX Glow", description = _T"full screen glow effect", type = "boolean" },
	["ffxNether"] = { prettyName = _T"FFX Nether", description = _T"full screen nether / glow effect", type = "boolean" },
	["releaseUITextures"] = { prettyName = _T"Release UI Textures", description = _T"Release Hidden UI Textures by default", type = "boolean" },
	["alwaysCompareItems"] = { prettyName = _T"Always Compare Items", description = _T"Always show item comparison tooltips", type = "boolean" },
	["showSpenderFeedback"] = { prettyName= "Show spender feedback", description = _T"Shows/Hide the flash after spending rage/mana/etc in resource bars.", type = "boolean" },
	-- Loss of Control UI
	["lossOfControlFull"] = { prettyName = _T"Loss of Control: Full", description = _T"Sets the type of the Loss of Control alert. (0 = Off, 1 = Only Alert, 2 = Show Full Duration)", type = "number" },
	["lossOfControlSilence"] = { prettyName = _T"Loss of Control: Silence", description = _T"Sets the type of the Loss of Control alert. (0 = Off, 1 = Only Alert, 2 = Show Full Duration)", type = "number" },
	["lossOfControlInterrupt"] = { prettyName = _T"Loss of Control: Interrupt", description = _T"Sets the type of the Loss of Control alert. (0 = Off, 1 = Only Alert, 2 = Show Full Duration)", type = "number" },
	["lossOfControlDisarm"] = { prettyName = _T"Loss of Control: Disarm", description = _T"Sets the type of the Loss of Control alert. (0 = Off, 1 = Only Alert, 2 = Show Full Duration)", type = "number" },
	["lossOfControlRoot"] = { prettyName = _T"Loss of Control: Root", description = _T"Sets the type of the Loss of Control alert. (0 = Off, 1 = Only Alert, 2 = Show Full Duration)", type = "number" },
	["synchronizeMacros"] = { prettyName = _T"Synchronize Macros", description = _T"Toggles synchronizing Macros with the server on/off", type = "boolean" },
	["synchronizeConfig"] = { prettyName = _T"Synchronize Config", description = _T"Toggles synchronizing settings with the server on/off", type = "boolean" },
	["cursorsizepreferred"] = { prettyName = _T"Cursor Size", description = _T"0 = 32x32, 1 = 48x48, 2 = 64x64, -1 = autodetect", type = "number" },
	["ffxDeath"] = { prettyName = _T"FFX Death", description = _T"Enables full screen death effect", type = "boolean" },
	["WorldTextScale"] = { prettyName = _T"World Text Scale", description = _T"The scale of in-world damage numbers, xp gain, artifact gains, etc", type = "number" },


	-- 7.1.5 dump (1/16/17)
	["BrowserNavigateLog"] = { description = _T"Enables Logging of browser navigation requests (Requires /reload)" },
	--["CACHE-WGOB-GameObjectsHotfixCount"] = {},
	--["CACHE-WGOB-GameObjectsRecordCount"] = {},
	--["CACHE-WQST-QuestObjectiveHotfixCount"] = {},
	--["CACHE-WQST-QuestObjectiveRecordCount"] = {},
	--["CACHE-WQST-QuestObjectiveXEffectHotfixCount"] = {},
	--["CACHE-WQST-QuestObjectiveXEffectRecordCount"] = {},
	--["CACHE-WQST-QuestV2HotfixCount"] = {},
	--["CACHE-WQST-QuestV2RecordCount"] = {},
	["ChatMusicVolume"] = {},
	["CombatHealingAbsorbSelf"] = {},
	["DepthBasedOpacity"] = {},
	["DesktopGamma"] = {},
	-- ["EJDungeonDifficulty"] = { description = _T"Stores the last dungeon difficulty viewed in the encounter journal" },
	-- ["EJLootClass"] = { description = _T"Stores the last class that loot was filtered by in the encounter journal" },
	-- ["EJLootSpec"] = { description = _T"Stores the last spec that loot was filtered by in the encounter journal" },
	-- ["EJRaidDifficulty"] = { description = _T"Stores the last raid difficulty viewed in the encounter journal" },
	["EmitterCombatrange"] = { description = _T"Range to stop shoulder/weapon emissions during combat" },
	-- ["ErrorFilter"] = {},
	-- ["ErrorLevelMax"] = {},
	-- ["ErrorLevelMin"] = {},
	-- ["Errors"] = {},
	["FootstepSounds"] = { description = _T"play footstep sounds" },
	["Gamma"] = {},
	["LodLiquid"] = { description = _T"Render using lod liquid" },
	["M2ForceAdditiveParticleSort"] = { description = _T"force all particles to sort as though they were additive" },
	["M2UseInstancing"] = { description = _T"use hardware instancing" },
	["M2UseLOD"] = { description = _T"use model lod" },
	["M2UseThreads"] = { description = _T"multithread model animations" },
	["MSAAAlphaTest"] = { description = _T"Enable MSAA for alpha-tested geometry" },
	["MSAAQuality"] = { description = _T"Multisampling AA quality" },
	["MaxObservedPetBattles"] = { description = _T"Maximum number of observed pet battles" },
	["NameplatePersonalHideDelayAlpha"] = { description = _T"Determines the alpha of the personal nameplate after no visibility conditions are met (during the period of time specified by NameplatePersonalHideDelaySeconds)." },
	["NonEmitterCombatRange"] = { description = _T"Range to stop shoulder/weapon emissions outside combat" },
	["ObjectSelectionCircle"] = {},
	["OutlineEngineMode"] = {},
	-- ["Outline"] = { description="Outline Mode" }, -- don't know what this does aside from make you flash when it's set
	["POIShiftComplete"] = {},
	-- ["PraiseTheSun"] = {},
	["PushToTalkButton"] = { description = _T"String representation of the Push-To-Talk button." },
	["RAIDDepthBasedOpacity"] = {},
	["RAIDLightMode"] = {},
	["RAIDOutlineEngineMode"] = {},
	["RAIDSSAO"] = {},
	["RAIDSSAOBlur"] = {},
	["RAIDWaterDetail"] = {},
	["RAIDcomponentTextureLevel"] = {},
	["RAIDenvironmentDetail"] = {},
	["RAIDfarclip"] = {},
	["RAIDgraphicsQuality"] = {},
	["RAIDgroundEffectDensity"] = {},
	["RAIDgroundEffectDist"] = {},
	["RAIDgroundEffectFade"] = { description = _T"Raid Ground effect fade" },
	["RAIDhorizonStart"] = { description = _T"Raid Horizon start distance" },
	["RAIDlodObjectCullDist"] = {},
	["RAIDlodObjectCullSize"] = {},
	["RAIDlodObjectMinSize"] = {},
	["RAIDlodObjectFadeScale"] = {},
	["RAIDparticleDensity"] = {},
	["RAIDparticleMTDensity"] = {},
	["RAIDprojectedTextures"] = {},
	["RAIDreflectionMode"] = {},
	["RAIDrefraction"] = {},
	["RAIDrippleDetail"] = {},
	["RAIDsettingsEnabled"] = { description = _T"Raid graphic settings are available" },
	["RAIDsettingsInit"] = {},
	["RAIDshadowMode"] = {},
	["RAIDshadowSoft"] = {},
	["RAIDshadowTextureSize"] = {},
	["RAIDsunShafts"] = {},
	["RAIDterrainLodDist"] = {},
	["RAIDterrainMipLevel"] = {},
	["RAIDterrainTextureLod"] = {},
	["RAIDtextureFilteringMode"] = {},
	["RAIDweatherDensity"] = {},
	["RAIDwmoLodDist"] = {},
	["RAIDworldBaseMip"] = {},
	["RenderScale"] = { description = _T"Render scale (for supersampling or undersampling)" },
	["ResampleQuality"] = { description = _T"Resample quality" },
	["SSAO"] = {},
	["SSAOBlur"] = {},
	["SSAODistance"] = { description = _T"SSAO distance" },
	["SkyCloudLOD"] = {},
	["SoundPerf_VariationCap"] = { description = _T"Limit sound kit variations to cut down on memory usage and disk thrashing on 32-bit machines" },
	["SoundUseNewBusSystem"] = { description = _T"use the new bus structure or fallback to the old one" },
	["Sound_DSPBufferSize"] = { description = _T"sound buffer size, default 0" },
	["Sound_EnableArmorFoleySoundForOthers"] = {},
	["Sound_EnableArmorFoleySoundForSelf"] = {},
	["Sound_EnableMixMode2"] = {},
	["Sound_EnableMode2"] = {},
	["Sound_MaxCacheSizeInBytes"] = { description = _T"Max cache size in bytes" },
	["Sound_MaxCacheableSizeInBytes"] = { description = _T"Max sound size that will be cached, larger files will be streamed instead" },
	["Sound_NumChannels"] = {},
	["Sound_OutputDriverIndex"] = {},
	["Sound_OutputDriverName"] = {},
	["Sound_OutputSampleRate"] = { description = _T"output sample rate" },
	["Sound_VoiceChatInputDriverIndex"] = {},
	["Sound_VoiceChatInputDriverName"] = {},
	["Sound_VoiceChatOutputDriverIndex"] = {},
	["Sound_VoiceChatOutputDriverName"] = {},
	["SplineOpt"] = { description = _T"toggles use of spline coll optimization" },
	["StartTalkingDelay"] = {},
	["StartTalkingTime"] = {},
	["StopTalkingDelay"] = {},
	["StopTalkingTime"] = {},
	["TargetPriorityValueBank"] = { description = _T"Selects the active targeting values bank for calculating target priority order" },
	["VoiceChatMode"] = { description = _T"Push to talk(0) or voice activation(1)" },
	["VoiceChatSelfMute"] = { description = _T"Turn off your ability to talk." },
	["WorldTextCritScreenY"] = {},
	["WorldTextGravity"] = {},
	["WorldTextNonRandomZ"] = {},
	["WorldTextRampDuration"] = {},
	["WorldTextRampPow"] = {},
	["WorldTextRampPowCrit"] = {},
	["WorldTextRandomXY"] = {},
	["WorldTextRandomZMax"] = {},
	["WorldTextRandomZMin"] = {},
	["WorldTextScreenY"] = {},
	["WorldTextStartPosRandomness"] = {},
	-- ["accounttype"] = {},
	-- ["actionedAdventureJournalEntries"] = { description = _T"Which adventure journal entries flagged with ADVENTURE_JOURNAL_HIDE_AFTER_ACTION the user acted upon" },
	-- ["activeCUFProfile"] = { description = _T"The last active CUF Profile." },
	-- ["addFriendInfoShown"] = { description = _T"The info for Add Friend has been shown" },
	-- ["advJournalLastOpened"] = { description = _T"Last time the Adventure Journal opened" },
	-- ["agentUID"] = { description = _T"The UID provided by Battle.net to be passed to Agent" },
	["allowCompareWithToggle"] = {},
	["allowD3D9BackingStore"] = { description = _T"Allow D3D9 to have texture backing to decrease load times and increase the chance of an out of memory crash" },
	["animFrameSkipLOD"] = { description = _T"animations will skip frames at distance" },
	["asyncHandlerTimeout"] = { description = _T"Engine option: Async read main thread timeout" },
	["asyncThreadSleep"] = { description = _T"Engine option: Async read thread sleep" },
	["auctionDisplayOnCharacter"] = { description = _T"Show auction items on the dress-up paperdoll" },
	["audioLocale"] = { description = _T"Set the game locale for audio content" },
	["autoCompleteResortNamesOnRecency"] = { description = _T"Shows people you recently spoke with higher up on the AutoComplete list." },
	["autoCompleteUseContext"] = { description = _T"The system will, for example, only show people in your guild when you are typing /gpromote. Names will also never be removed." },
	["autoCompleteWhenEditingFromCenter"] = { description = _T"If you edit a name by inserting characters into the center, a smarter auto-complete will occur." },
	["autoDismount"] = { description = _T"Automatically dismount when needed" },
	-- ["autoFilledMultiCastSlots"] = { description = _T"Bitfield that saves whether multi-cast slots have been automatically filled." },
	-- ["autoQuestPopUps"] = { description = _T"Saves current pop-ups for quests that are automatically acquired or completed." },
	["autoStand"] = { description = _T"Automatically stand when needed" },
	["autoUnshift"] = { description = _T"Automatically leave shapeshift form when needed" },
	["autojoinBGVoice"] = { description = _T"Automatically join the voice session in battleground chat" },
	["autojoinPartyVoice"] = { description = _T"Automatically join the voice session in party/raid chat" },
	-- ["bloatTest"] = {},
	-- ["bloatnameplates"] = {},
	-- ["bloatthreat"] = {},
	["bodyQuota"] = { description = _T"Maximum number of componented bodies seen at once" },
	["breakUpLargeNumbers"] = { description = _T"Toggles using commas in large numbers" },
	["bspcache"] = { description = _T"BSP node caching" },
	["calendarShowBattlegrounds"] = { description = _T"Whether Battleground holidays should appear in the calendar" },
	["calendarShowDarkmoon"] = { description = _T"Whether Darkmoon Faire holidays should appear in the calendar" },
	["calendarShowLockouts"] = { description = _T"Whether raid lockouts should appear in the calendar" },
	["calendarShowResets"] = { description = _T"Whether raid resets should appear in the calendar" },
	["calendarShowWeeklyHolidays"] = { description = _T"Whether weekly holidays should appear in the calendar" },
	["cameraCustomViewSmoothing"] = {},
	["cameraDistanceMax"] = {},
	["cameraDistanceMaxFactor"] = {},
	["cameraDistanceRateMult"] = {},
	["cameraDive"] = {},
	["cameraHeightIgnoreStandState"] = {},
	["cameraPitchSmoothMax"] = {},
	["cameraPitchSmoothMin"] = {},
	["cameraPivotDXMax"] = {},
	["cameraPivotDYMin"] = {},
	-- ["cameraSavedDistance"] = {},
	-- ["cameraSavedPetBattleDistance"] = {},
	-- ["cameraSavedPitch"] = {},
	-- ["cameraSavedVehicleDistance"] = {},
	-- ["cameraView"] = {},
	["cameraYawSmoothMax"] = {},
	["cameraYawSmoothMin"] = {},
	["cameraZDamp"] = {},
	["cameraZoomSpeed"] = {},
	-- ["characterFrameCollapsed"] = {},
	["chatStyle"] = { description = _T"The style of Edit Boxes for the ChatFrame. Valid values: \"classic\", \"im\"" },
	["checkAddonVersion"] = {},
	["cloakFixEnabled"] = {},
	-- ["closedInfoFrames"] = { description = _T"Bitfield for which help frames have been acknowledged by the user" },
	["colorChatNamesByClass"] = { description = _T"If enabled, the name of a player speaking in chat will be colored according to his class." },
	["combatLogReducedRetentionTime"] = { description = _T"The maximum duration in seconds to retain combat log entries when we're low on memory" },
	["combatLogRetentionTime"] = { description = _T"The maximum duration in seconds to retain combat log entries" },
	["combatTextFloatMode"] = {},
	["componentCompress"] = { description = _T"Character component texture compression" },
	["componentEmissive"] = { description = _T"Character component unlit/emissive" },
	["componentSpecular"] = { description = _T"DISABLED FOR 7.0.3 - Character component specular highlights" },
	["componentTexCacheSize"] = { description = _T"Character component texture cache size (in MB)" },
	["componentTexLoadLimit"] = { description = _T"Character component texture loading limit per frame" },
	["componentTextureLevel"] = {},
	["componentThread"] = { description = _T"Multi thread character component processing" },
	-- ["currencyCategoriesCollapsed"] = { description = _T"Internal CVar for tracking collapsed currency categories." },
	-- ["currencyTokensBackpack1"] = { description = _T"Currency token types shown on backpack." },
	-- ["currencyTokensBackpack2"] = { description = _T"Currency token types shown on backpack." },
	-- ["currencyTokensUnused1"] = { description = _T"Currency token types marked as unused." },
	-- ["currencyTokensUnused2"] = { description = _T"Currency token types marked as unused." },
	["daltonize"] = { description = _T"Attempt to correct for color blindness (set colorblindSimulator to type of colorblindness)" },
	-- ["dangerousShipyardMissionWarningAlreadyShown"] = { description = _T"Boolean indicating whether the shipyard's dangerous mission warning has been shown" },
	-- ["debugSoundPlayerSpellsOnlyOnPlayerBus"] = {},
	["detailDoodadInstancing"] = { description = _T"Detail doodad instancing" },
	["digSites"] = { description = _T"If enabled, the archaeological dig site system will be used." },
	["disableAutoRealmSelect"] = { description = _T"Disable automatically selecting a realm on login" },
	["displayWorldPVPObjectives"] = { description = _T"Whether to show world PvP objectives" },
	-- ["displayedRAFFriendInfo"] = { description = _T"Stores whether we already told a recruited person about their new BattleTag friend" },
	["dontShowEquipmentSetsOnItems"] = { description = _T"Don't show which equipment sets an item is associated with" },
	["doodadLodDist"] = { description = _T"Doodad level of detail distance" },
	["doodadUnloadDist"] = {},
	["enableBGDL"] = { description = _T"Background Download (on async net thread) Enabled" },
	-- ["enableCombatText"] = {},
	["enablePVPNotifyAFK"] = { description = _T"The ability to shutdown the AFK notification system" },
	["enablePetBattleFloatingCombatText"] = { description = _T"Whether to show floating combat text for pet battles" },
	-- ["engineSurvey"] = {},
	["enterWorld"] = {},
	["entityLodDist"] = { description = _T"Entity level of detail distance" },
	["environmentDetail"] = {},
	["expandUpgradePanel"] = {},
	["farclip"] = {},
	["fctCombatState"] = {},
	-- ["fctFriendlyHealers"] = {},
	["ffxAntiAliasingMode"] = { description = _T"Anti Aliasing Mode" },
	["ffxRectangle"] = { description = _T"use rectangle texture for full screen effects" },
	-- ["flaggedTutorials"] = { description = _T"Internal cvar for saving completed tutorials in order" },
	["flightAngleLookAhead"] = { description = _T"Enables more dynamic attitude adjustments while flying" },
	-- ["floatingCombatTextCombatDamageStyle"] = { description = _T"No longer used" },
	["forceEnglishNames"] = {},
	["forceLODCheck"] = { description = _T"If enabled, we will skip checking DBC for LOD count and every m2 will scan the folder for skin profiles" },
	-- ["friendInvitesCollapsed"] = { description = _T"Whether friend invites are hidden in the friends list" },
	["friendsSmallView"] = { description = _T"Whether to use smaller buttons in the friends list" },
	["friendsViewButtons"] = { description = _T"Whether to show the friends list view buttons" },
	["fullDump"] = { description = _T"When you crash, generate a full memory dump" },
	["gameTip"] = {},
	["garrisonCompleteTalent"] = {},
	["garrisonCompleteTalentType"] = {},
	["graphicsDepthEffects"] = { description = _T"UI value of the graphics setting" },
	["graphicsEnvironmentDetail"] = {},
	["graphicsLightingQuality"] = { description = _T"UI value of the graphics setting" },
	["graphicsLiquidDetail"] = { description = _T"UI value of the graphics setting" },
	["graphicsOutlineMode"] = { description = _T"UI value of the graphics setting" },
	["graphicsParticleDensity"] = {},
	["graphicsProjectedTextures"] = { description = _T"UI value of the graphics setting" },
	["graphicsQuality"] = {},
	["graphicsSSAO"] = { description = _T"UI value of the graphics setting" },
	["graphicsShadowQuality"] = {},
	["graphicsSunshafts"] = { description = _T"UI value of the graphics setting" },
	["graphicsTextureFiltering"] = {},
	["graphicsTextureResolution"] = {},
	["graphicsViewDistance"] = {},
	["groundEffectDensity"] = {},
	["groundEffectDist"] = {},
	["groundEffectFade"] = { description = _T"Ground effect fade" },
	-- ["guildNewsFilter"] = { description = _T"Stores the guild news filters" },
	["guildRewardsCategory"] = { description = _T"Show category of guild rewards" },
	["guildRewardsUsable"] = { description = _T"Show usable guild rewards only" },
	-- ["guildRosterView"] = { description = _T"The current guild roster display mode" },
	["guildShowOffline"] = { description = _T"Show offline guild members in the guild UI" },
	["gxAFRDevicesCount"] = { description = _T"Force to set number of AFR devices" },
	["gxAdapter"] = { description = _T"Force to run the specified adapter index (-1 to let client choose)" },
	-- ["gxApi"] = {},
	["gxAspect"] = { description = _T"constrain window aspect" },
	["gxCursor"] = { description = _T"toggle hardware cursor" },
	["gxDepthResolveHandleCaching"] = { description = _T"Caching of the target handle for the depth resolve" },
	["gxFixLag"] = { description = _T"prevent cursor lag" },
	["gxFullscreenResolution"] = { description = _T"resolution" },
	["gxMaxFrameLatency"] = { description = _T"maximum number of frames ahead of GPU the CPU can be" },
	["gxMaximize"] = {},
	["gxMonitor"] = { description = _T"monitor" },
	["gxNewResolution"] = { description = _T"resolution to be set" },
	["gxPreferWindowedFullscreen"] = { description = _T"prefer which fullscreen mode for toggle" },
	-- ["gxRefresh"] = {},
	["gxStereoConvergence"] = { description = _T"Set stereoscopic rendering convergence depth" },
	["gxStereoEnabled"] = { description = _T"Enable stereoscopic rendering" },
	["gxStereoSeparation"] = { description = _T"Set stereoscopic rendering separation percentage" },
	["gxTextureCacheSize"] = { description = _T"GX Texture Cache Size" },
	["gxTripleBuffer"] = { description = _T"triple buffer" },
	["gxVSync"] = { description = _T"vsync on or off" },
	["gxWindow"] = {},
	["gxWindowedResolution"] = {},
	-- ["hardTrackedQuests"] = { description = _T"Internal cvar for saving hard (user manually selected) tracked quests in order" },
	-- ["hardTrackedWorldQuests"] = { description = _T"Internal cvar for saving hard tracked world quests" },
	["hbaoBias"] = { description = _T"HBAO Bias" },
	["hbaoBlurSharp"] = { description = _T"HBAO Blur Sharpness" },
	["hbaoNormals"] = { description = _T"Use Normals for HBAO" },
	["hbaoPowerExp"] = { description = _T"HBAO Power Exponent" },
	["hbaoRadius"] = { description = _T"HBAO Radius" },
	-- ["heirloomCollectedFilters"] = { description = _T"Bitfield for which collected filters are applied in the heirloom journal" },
	-- ["heirloomSourceFilters"] = { description = _T"Bitfield for which source filters are applied in the heirloom journal" },
	["hideAdventureJournalAlerts"] = { description = _T"Hide alerts shown on the Adventure Journal Microbutton" },
	["horizonStart"] = {},
	["hotReloadModels"] = { description = _T"Allow an active model to be reloaded when a new version is detected in the bin folder. If this is disabled, the model data will only be refreshed after all game objects using the model are deleted" },
	["hwDetect"] = {},
	["hwPCF"] = { description = _T"Hardware PCF Filtering" },
	["incompleteQuestPriorityThresholdDelta"] = {},
	["initialRealmListTimeout"] = { description = _T"How long to wait for the initial realm list before failing login (in seconds)" },
	["installLocale"] = {},
	--["installType"] = {},
	-- ["lastAddonVersion"] = {},
	-- ["lastCharacterIndex"] = {},
	-- ["lastGarrisonMissionTutorial"] = { description = _T"Stores the last garrison mission tutorial the player has accepted" },
	-- ["lastReadEULA"] = {},
	-- ["lastReadTOS"] = {},
	-- ["lastReadTerminationWithoutNotice"] = {},
	-- ["lastTalkedToGM"] = { description = _T"Stores the last GM someone was talking to in case they reload the UI while the GM chat window is open." },
	-- ["lastTransmogOutfitID"] = { description = _T"SetID of the last loaded transmog outfit" },
	-- ["lastVoidStorageTutorial"] = { description = _T"Stores the last void storage tutorial the player has accepted" },
	["launchAgent"] = { description = _T"Set this to have the client start up Agent" },
	-- ["lfGuildComment"] = { description = _T"Stores the player's Looking For Guild comment" },
	-- ["lfGuildSettings"] = { description = _T"Bit field of Looking For Guild player settings" },
	-- ["lfdCollapsedHeaders"] = { description = _T"Stores which LFD headers are collapsed." },
	-- ["lfdSelectedDungeons"] = { description = _T"Stores which LFD dungeons are selected." },
	["lfgAutoFill"] = { description = _T"Whether to automatically add party members while looking for a group" },
	["lfgAutoJoin"] = { description = _T"Whether to automatically join a party while looking for a group" },
	-- ["lfgListSearchLanguages"] = { description = _T"A simple bitfield for what languages we want to search in." },
	-- ["lfgSelectedRoles"] = { description = _T"Stores what roles the player is willing to take on." },
	["lightMode"] = {},
	["locale"] = { description = _T"Set the game locale" },
	["lockedWorldMap"] = { description = _T"Whether the world map is locked when sized down" },
	["lodObjectCullDist"] = {},
	["lodObjectCullSize"] = {},
	["lodObjectMinSize"] = {},
	["lodTerrainDiv"] = { description = _T"Terrain lod divisor" },
	["mapAnimDuration"] = { description = _T"Duration for the alpha animation" },
	["mapAnimMinAlpha"] = { description = _T"Alpha value to animate to when player moves with windowed world map open" },
	["mapAnimStartDelay"] = { description = _T"Start delay for the alpha animation" },
	["mapQuestDifficulty"] = {},
	-- ["maxAnimThreads"] = {},
	["maxFPS"] = { description = _T"Set FPS limit" },
	["maxFPSBk"] = { description = _T"Set background FPS limit" },
	["maxLightCount"] = { description = _T"Maximum lights to render" },
	["maxLightDist"] = { description = _T"Maximum distance to render lights" },
	["miniWorldMap"] = { description = _T"Whether or not the world map has been toggled to smaller size" },
	["minimapAltitudeHintMode"] = { description = _T"Change minimap altitude difference display. 0=none, 1=darken, 2=arrows" },
	["minimapInsideZoom"] = { description = _T"The current indoor minimap zoom level" },
	["minimapPortalMax"] = { description = _T"Max Number of Portals to traverse for minimap" },
	-- ["minimapShapeshiftTracking"] = { description = _T"Stores shapeshift-specific tracking spells that were active last session." },
	["minimapShowArchBlobs"] = { description = _T"Stores whether to show archaeology blobs on the minimap." },
	["minimapShowQuestBlobs"] = { description = _T"Stores whether to show the quest blobs on the minimap." },
	-- ["minimapTrackedInfo"] = {},
	-- ["minimapTrackedInfov2"] = { description = _T"Stores the minimap tracking that was active last session." },
	["minimapZoom"] = { description = _T"The current outdoor minimap zoom level" },
	["missingTransmogSourceInItemTooltips"] = { description = _T"Whether to show if you have collected the appearance of an item but not from that item itself" },
	-- ["mountJournalFilters"] = { description = _T"Bitfield for which collected filters are applied in the mount journal" },
	-- ["mountJournalSourceFilters"] = { description = _T"Bitfield for which source filters are applied in the mount journal" },
	["mouseInvertYaw"] = {},
	["mtParticles"] = { description = _T"multithread building of particle vertices" },
	["nameplateMotionSpeed"] = { description = _T"Controls the rate at which nameplate animates into their target locations [0.0-1.0]" },
	["nameplateShowEnemyMinions"] = {},
	["nameplateShowFriendlyMinions"] = {},
	["nearclip"] = { description = _T"Near clip plane distance" },
	-- ["orderHallMissionTutorial"] = { description = _T"Stores information about which order hall mission tutorials the player has seen" },
	["outdoorMinAltitudeDistance"] = { description = _T"Minimum altitude distance for outdoor objects when you are also outdoors before the altitude difference marker displays" },
	["outlineMouseOverFadeDuration"] = {},
	["outlineSelectionFadeDuration"] = {},
	["overrideArchive"] = { description = _T"Whether or not the client loads alternate data" },
	["particleDensity"] = {},
	["particleMTDensity"] = {},
	["partyBackgroundOpacity"] = { description = _T"The opacity of the party background" },
	["pathSmoothing"] = { description = _T"NPC will round corners on ground paths" },
	-- ["pendingInviteInfoShown"] = { description = _T"The info for pending invites has been shown" },
	-- ["petJournalFilters"] = { description = _T"Bitfield for which collected filters are applied in the pet journal" },
	-- ["petJournalSort"] = { description = _T"Sorting value for the pet journal" },
	-- ["petJournalSourceFilters"] = { description = _T"Bitfield for which source filters are applied in the pet journal" },
	-- ["petJournalTab"] = { description = _T"Stores the last tab the pet journal was opened to" },
	-- ["petJournalTypeFilters"] = { description = _T"Bitfield for which type filters are applied in the pet journal" },
	["physicsLevel"] = { description = _T"Level of physics world interaction" },
	["playIntroMovie"] = {},
	--["playerStatLeftDropdown"] = { description = _T"The player stat selected in the left dropdown" },
	--["playerStatRightDropdown"] = { description = _T"The player stat selected in the right dropdown" },
	-- ["portal"] = { description = _T"Name of Battle.net portal to use" },
	["predictedHealth"] = { description = _T"Whether or not to use predicted health values in the UI" },
	["preloadLoadingDistObject"] = { description = _T"Object preload distance when loading" },
	["preloadLoadingDistTerrain"] = { description = _T"Terrain preload distance when loading" },
	["preloadPlayerModels"] = { description = _T"Preload all local racial models into memory" },
	["preloadStreamingDistObject"] = { description = _T"Object preload distance when streaming" },
	["preloadStreamingDistTerrain"] = { description = _T"Terrain preload distance when streaming" },
	["primaryProfessionsFilter"] = { description = _T"If enabled, primary profession world quests icons will be shown on world maps" },
	["processAffinityMask"] = { description = _T"Sets which core(s) WoW may execute on - changes require restart to take effect" },
	["projectedTextures"] = {},
	["pvpBlacklistMaps0"] = { description = _T"Blacklist PVP Map" },
	["pvpBlacklistMaps1"] = { description = _T"Blacklist PVP Map" },
	-- ["pvpSelectedRoles"] = { description = _T"Stores what roles the player will fulfill in a BG." },
	-- ["questLogCollapseFilter"] = {},
	-- ["questLogCollapseHeaderFilter"] = {},
	-- ["questLogOpen"] = { description = _T"Whether the quest log appears the side of the windowed map. " },
	["questPOI"] = { description = _T"If enabled, the quest POI system will be used." },
	["raidFramesDisplayAggroHighlight"] = { description = _T"Whether to display aggro highlights on Raid Frames" },
	["raidFramesDisplayClassColor"] = { description = _T"Colors raid frames with the class color" },
	["raidFramesDisplayOnlyDispellableDebuffs"] = { description = _T"Whether to display only dispellable debuffs on Raid Frames" },
	["raidFramesDisplayPowerBars"] = { description = _T"Whether to display mana, rage, etc. on Raid Frames" },
	["raidFramesHealthText"] = { description = _T"How to display health text on the raid frames" },
	["raidFramesHeight"] = { description = _T"The height of the individual raid frames" },
	["raidFramesPosition"] = { description = _T"Where the raid frames should be placed" },
	["raidFramesWidth"] = { description = _T"The width of the individual raid frames" },
	["raidGraphicsDepthEffects"] = {},
	["raidGraphicsEnvironmentDetail"] = {},
	["raidGraphicsGroundClutter"] = {},
	["raidGraphicsLightingQuality"] = {},
	["raidGraphicsLiquidDetail"] = {},
	["raidGraphicsOutlineMode"] = {},
	["raidGraphicsParticleDensity"] = {},
	["raidGraphicsProjectedTextures"] = {},
	["raidGraphicsSSAO"] = {},
	["raidGraphicsShadowQuality"] = {},
	["raidGraphicsSunshafts"] = {},
	["raidGraphicsTextureFiltering"] = {},
	["raidGraphicsTextureResolution"] = {},
	["raidGraphicsViewDistance"] = {},
	["raidOptionDisplayMainTankAndAssist"] = { description = _T"Whether to display main tank and main assist units in the raid frames" },
	["raidOptionDisplayPets"] = { description = _T"Whether to display pets on the raid frames" },
	["raidOptionIsShown"] = { description = _T"Whether the Raid Frames are shown" },
	["raidOptionKeepGroupsTogether"] = { description = _T"The way to group raid frames" },
	["raidOptionLocked"] = { description = _T"Whether the raid frames are locked" },
	["raidOptionShowBorders"] = { description = _T"Displays borders around the raid frames." },
	["raidOptionSortMode"] = { description = _T"The way to sort raid frames" },
	["raidOrBattleCount"] = {},
	["rawMouseAccelerationEnable"] = { description = _T"Enable acceleration for raw mouse input" },
	["rawMouseEnable"] = { description = _T"Enable raw mouse input" },
	["rawMouseRate"] = { description = _T"Raw mouse update rate" },
	["rawMouseResolution"] = { description = _T"Raw mouse resolution" },
	--["readContest"] = {},
	--["readEULA"] = {},
	--["readScanning"] = {},
	--["readTOS"] = {},
	--["readTerminationWithoutNotice"] = {},
	-- ["realmName"] = {},
	["reflectionDownscale"] = { description = _T"Reflection downscale" },
	["reflectionMode"] = {},
	["refraction"] = {},
	["repositionfrequency"] = {},
	-- ["reputationsCollapsed"] = { description = _T"List of reputation categories that have been collapsed in the Reputation tab" },
	["rippleDetail"] = {},
	["sceneOcclusionEnable"] = { description = _T"Scene software occlusion" },
	["screenshotFormat"] = {},
	["screenshotQuality"] = {},
	["scriptProfile"] = { description = _T"Whether or not script profiling is enabled" },
	["scriptWarnings"] = { description = _T"Whether or not the UI shows Lua warnings" },
	["secondaryProfessionsFilter"] = { description = _T"If enabled, secondary profession world quests icons will be shown on world maps" },
	-- ["seenAsiaCharacterUpgradePopup"] = { description = _T"Seen the free character upgrade popup (Asia)" },
	-- ["seenCharacterUpgradePopup"] = {},
	-- ["serverAlert"] = { description = _T"Get the glue-string tag for the URL" },
	-- ["serviceTypeFilter"] = { description = _T"Which trainer services to show" },
	["shadowCull"] = { description = _T"enable shadow frustum culling" },
	["shadowInstancing"] = { description = _T"enable instancing when rendering shadowmaps" },
	["shadowMode"] = {},
	["shadowScissor"] = { description = _T"enable scissoring when rendering shadowmaps" },
	["shadowSoft"] = {},
	["shadowTextureSize"] = {},
	-- ["shipyardMissionTutorialAreaBuff"] = { description = _T"Stores whether the player has accepted the first area buff mission tutorial" },
	-- ["shipyardMissionTutorialBlockade"] = { description = _T"Stores whether the player has accepted the first blockade mission tutorial" },
	-- ["shipyardMissionTutorialFirst"] = { description = _T"Stores whether the player has accepted the first mission tutorial" },
	["showAllEnemyDebuffs"] = {},
	["showArtifactXPBar"] = { description = _T"Show the artifact xp as priority over reputation" },
	["showBattlefieldMinimap"] = { description = _T"Whether or not the battlefield minimap is shown" },
	["showBuilderFeedback"] = { description = _T"Show animation when building power for builder/spender bar" },
	["showErrors"] = {},
	["showKeyring"] = {},
	["showNPETutorials"] = { description = _T"display NPE tutorials" },
	["showNewbieTips"] = {},
	["showQuestObjectivesOnMap"] = { description = _T"Shows quest POIs on the main map." },
	["showQuestTrackingTooltips"] = { description = _T"Displays quest tracking information in unit and object tooltips" },
	["showSpectatorTeamCircles"] = { description = _T"Determines if the team color circles are visible while spectating or commentating a wargame" },
	["showTamers"] = { description = _T"If enabled, pet battle icons will be shown on world maps" },
	["showTimestamps"] = { description = _T"The format of timestamps in chat or \"none\"" },
	-- ["showTokenFrame"] = { description = _T"The token UI has been shown" },
	-- ["showTokenFrameHonor"] = { description = _T"The token UI has shown Honor" },
	-- ["showToolsUI"] = {},
	["showfootprintparticles"] = { description = _T"toggles rendering of footprint particles" },
	["simd"] = { description = _T"Enable SIMD features (e.g. SSE)" },
	["skipStartGear"] = { description = _T"Whether we should show starter gear on character create" },
	["smoothUnitPhasing"] = { description = _T"The client will try to smoothly switch between the same on model different phases." },
	["smoothUnitPhasingActorPurgatoryTimeMs"] = { description = _T"Time to keep client-actor displays in purgatory before letting go of them, if they were despawned" },
	["smoothUnitPhasingAliveTimeoutMs"] = { description = _T"Time to wait for an alive unit to get it's despawn message" },
	["smoothUnitPhasingDestroyedPurgatoryTimeMs"] = { description = _T"Time to keep unit displays in purgatory before letting go of them, if they were destroyed" },
	["smoothUnitPhasingDistThreshold"] = { description = _T"Distance threshold to active smooth unit phasing." },
	["smoothUnitPhasingEnableAlive"] = { description = _T"Use units that have not despawn yet if they match, in hopes the despawn message will come later." },
	["smoothUnitPhasingUnseenPurgatoryTimeMs"] = { description = _T"Time to keep unit displays in purgatory before letting go of them, if they were just unseen." },
	["smoothUnitPhasingVehicleExtraTimeoutMs"] = { description = _T"Extra time to wait before releasing a vehicle, after it has smooth phased. This allows it's passengers to smooth phase as well." },
	["spellBookSort"] = {},
	["spellClutter"] = { description = _T"Enables/Disables spell clutter" },
	["spellClutterDefaultTargetScalar"] = { description = _T"Starting target scalar value (min 0.1)" },
	["spellClutterHostileScalar"] = { description = _T"Scalar we apply to the hostile creature spells (min 0.001)" },
	["spellClutterMinSpellCount"] = { description = _T"Min spells on a target before we apply clutter logic (min 0)" },
	["spellClutterPartySizeScalar"] = { description = _T"Scales the targetScalar by how different the party size is from this (min 1)" },
	["spellClutterPlayerScalarMultiplier"] = { description = _T"Increases number of effects on \"interesting\" targets multiplicatively (min 0.1)" },
	["spellClutterRangeConstant"] = { description = _T"How many yards before the priority is doubled (min 1.0)" },
	["splashScreenBoost"] = { description = _T"Show boost splash screen id " },
	["splashScreenNormal"] = { description = _T"Show normal splash screen id" },
	-- ["statCategoriesCollapsed"] = {},
	-- ["statCategoriesCollapsed_2"] = {},
	-- ["statCategoryOrder"] = {},
	-- ["statCategoryOrder_2"] = {},
	["streamBeams"] = { description = _T"Use vertex streaming for beams (Gfx Driver Workaround). 0=Auto Detect, 1=Never Stream, 2=Always Stream" },
	["streamStatusMessage"] = { description = _T"Whether to display status messages while streaming content" },
	["streamingCameraLookAheadTime"] = { description = _T"Look ahead time for streaming." },
	["streamingCameraMaxRadius"] = { description = _T"Max radius of the streaming camera." },
	["streamingCameraRadius"] = { description = _T"Base radius of the streaming camera." },
	["sunShafts"] = {},
	["superTrackerDist"] = {},
	["synchronizeBindings"] = {},
	["synchronizeChatFrames"] = {},
	["synchronizeSettings"] = { description = _T"Whether client settings should be stored on the server" },
	["taintLog"] = {},
	-- ["talentFrameShown"] = { description = _T"The talent UI has been shown" },
	["talentPointsSpent"] = { description = _T"The player has spent a talent point" },
	["targetOfTargetMode"] = { description = _T"The conditions under which target of target should be shown" },
	["terrainAlphaBitDepth"] = { description = _T"Terrain alpha map bit depth" },
	["terrainHoles"] = { description = _T"Terrain holes affect occlusion" },
	["terrainLodDist"] = {},
	["terrainMipLevel"] = {},
	["terrainTextureLod"] = {},
	["test_cameraDynamicPitch"] = { description = _T"ActionCam" },
	["test_cameraDynamicPitchBaseFovPad"] = { description = _T"ActionCam" },
	["test_cameraDynamicPitchBaseFovPadDownScale"] = { description = _T"ActionCam" },
	["test_cameraDynamicPitchBaseFovPadFlying"] = { description = _T"ActionCam" },
	["test_cameraDynamicPitchSmartPivotCutoffDist"] = { description = _T"ActionCam" },
	["test_cameraHeadMovementDeadZone"] = { description = _T"ActionCam" },
	["test_cameraHeadMovementFirstPersonDampRate"] = { description = _T"ActionCam" },
	["test_cameraHeadMovementMovingDampRate"] = { description = _T"ActionCam" },
	["test_cameraHeadMovementMovingStrength"] = { description = _T"ActionCam" },
	["test_cameraHeadMovementRangeScale"] = { description = _T"ActionCam" },
	["test_cameraHeadMovementStandingDampRate"] = { description = _T"ActionCam" },
	["test_cameraHeadMovementStandingStrength"] = { description = _T"ActionCam" },
	["test_cameraHeadMovementStrength"] = { description = _T"ActionCam" },
	["test_cameraLockedTargetFocusing"] = { description = _T"ActionCam" },
	["test_cameraOverShoulder"] = { description = _T"ActionCam" },
	["test_cameraTargetFocusEnemyEnable"] = { description = _T"ActionCam" },
	["test_cameraTargetFocusEnemyStrengthPitch"] = { description = _T"ActionCam" },
	["test_cameraTargetFocusEnemyStrengthYaw"] = { description = _T"ActionCam" },
	["test_cameraTargetFocusInteractEnable"] = { description = _T"ActionCam" },
	["test_cameraTargetFocusInteractStrengthPitch"] = { description = _T"ActionCam" },
	["test_cameraTargetFocusInteractStrengthYaw"] = { description = _T"ActionCam" },
	["textLocale"] = { description = _T"Set the game locale for text" },
	["textureFilteringMode"] = {},
	["threatWarning"] = { description = _T"Whether or not to show threat warning UI (0 = off, 1 = in dungeons, 2 = in party/raid, 3 = always)" },
	["threatWorldText"] = { description = _T"Whether or not to show threat floaters in combat" },
	["timeMgrAlarmEnabled"] = { description = _T"Toggles whether or not the time manager's alarm will go off" },
	["timeMgrAlarmMessage"] = { description = _T"The time manager's alarm message" },
	["timeMgrAlarmTime"] = { description = _T"The time manager's alarm time in minutes" },
	["timeMgrUseLocalTime"] = { description = _T"Toggles the use of either the realm time or your system time" },
	["timeMgrUseMilitaryTime"] = { description = _T"Toggles the display of either 12 or 24 hour time" },
	["timingMethod"] = { description = _T"Desired method for game timing" },
	-- ["timingTestError"] = { description = _T"Error reported by the timing validation system" }, -- read-only
	-- ["toyBoxCollectedFilters"] = { description = _T"Bitfield for which collected filters are applied in the toybox" },
	-- ["toyBoxSourceFilters"] = { description = _T"Bitfield for which source filters are applied in the toybox" },
	-- ["trackedAchievements"] = { description = _T"Internal cvar for saving tracked achievements in order" },
	-- ["trackedQuests"] = { description = _T"Internal cvar for saving automatically tracked quests in order" },
	-- ["trackedWorldQuests"] = { description = _T"Internal cvar for saving tracked world quests" },
	-- ["trackerFilter"] = {},
	-- ["trackerSorting"] = {},
	["transmogCurrentSpecOnly"] = { description = _T"Stores whether transmogs apply to current spec instead of all specs" },
	-- ["transmogrifyShowCollected"] = { description = _T"Whether to show collected transmogs in the at the transmogrifier" }, -- read-only
	-- ["transmogrifyShowUncollected"] = { description = _T"Whether to show uncollected transmogs in the at the transmogrifier" }, -- read-only
	-- ["transmogrifySourceFilters"] = { description = _T"Bitfield for which source filters are applied in the wardrobe at the transmogrifier" },
	["twitterCharactersPerMedia"] = { description = _T"Number of characters needed when attaching media to a Twitter post" },
	-- ["twitterGetConfigTime"] = { description = _T"Last time that we got Twitter configuration data successfully" },
	["twitterShortUrlLength"] = { description = _T"Number of characters that non-https URLS get shortened to" },
	["twitterShortUrlLengthHttps"] = { description = _T"Number of characters that https URLS get shortened to" },
	["uiScale"] = {},
	["uiScaleMultiplier"] = { description = _T"A multiplier for the default UI scale. -1=determine based on system/monitor DPI, 0.5-2.0=multiplier to use when calculating UI scale. Only applied when useUIScale is 0." },
	["unitHighlights"] = { description = _T"Whether the highlight circle around units should be displayed" },
	["useCompactPartyFrames"] = { description = _T"Use the new raid frames for parties" },
	["useUiScale"] = {},
	["videoOptionsVersion"] = {},
	-- ["wardrobeShowCollected"] = { description = _T"Whether to show collected transmogs in the wardrobe" }, -- read-only
	-- ["wardrobeShowUncollected"] = { description = _T"Whether to show uncollected transmogs in the wardrobe" }, -- read-only
	-- ["wardrobeSourceFilters"] = { description = _T"Bitfield for which source filters are applied in the wardrobe in the collection journal" },
	["warp"] = { description = _T"UI value of the graphics setting" },
	["warpScreenSize"] = { description = _T"Physical monitor size" },
	["warpViewDistance"] = { description = _T"Physical distance from the viewer to the monitor" },
	["warpViewTilt"] = { description = _T"Angle of the side monitors IN RADIANS" },
	["watchFrameBaseAlpha"] = { description = _T"Objectives frame opacity." },
	-- ["watchFrameState"] = { description = _T"Stores Objectives frame locked and collapsed states" },
	["waterDetail"] = {},
	["weatherDensity"] = {},
	["webChallengeURLTimeout"] = { description = _T"How long to wait for the web challenge URL (in seconds). 0 means wait forever." },
	["whisperMode"] = { description = _T"The action new whispers take by default: \"popout\", \"inline\", \"popout_and_inline\"" },
	["windowResizeLock"] = { description = _T"prevent resizing in windowed mode" },
	["wmoDoodadDist"] = { description = _T"Wmo doodad load distance" },
	["wmoLodDist"] = {},
	["worldBaseMip"] = {},
	["worldLoadSort"] = { description = _T"Sort objects by distance when loading" },
	["worldMapOpacity"] = { description = _T"Opacity for the world map when sized down" },
	["worldMaxMipLevel"] = { description = _T"World maximum texture mip level" },
	["worldPoolUsage"] = { description = _T"Usage static/dynamic/stream" },
	["worldPreloadHighResTextures"] = { description = _T"Require high res textures to be loaded in streaming non critical radius when preloading" },
	["worldPreloadNonCritical"] = { description = _T"Require objects to be loaded in streaming non critical radius when preloading" },
	["worldPreloadSort"] = { description = _T"Sort objects by distance when preloading" },
	["worldQuestFilterArtifactPower"] = { description = _T"If enabled, world quests with artifact power rewards will be shown on the map" },
	["worldQuestFilterEquipment"] = { description = _T"If enabled, world quests with equipment rewards will be shown on the map" },
	["worldQuestFilterGold"] = { description = _T"If enabled, world quests with gold rewards will be shown on the map" },
	["worldQuestFilterOrderResources"] = { description = _T"If enabled, world quests with order resource rewards will be shown on the map" },
	["worldQuestFilterProfessionMaterials"] = { description = _T"If enabled, world quests with profession material rewards will be shown on the map" },
	["CastTimingEnhancements"] = { prettyName = nil, description = _T"Hold chain precasts, and predict anim timed casts", type = "boolean" },
	["autoAcceptQuickJoinRequests"] = { prettyName = _T"Auto-accept quick join requests", description = _T"", type = "boolean" },
	
	["AimingStrafeLeftUsesMoveBackwards"] = { description = _T"Uses backwards move anim when aiming a ranged weapon and strafing to the left" },
	["DebugTorsoTwist"] = { description = _T"Debug visualization for Torso Twist: 1 = Player, 2 = Target, 3 = All" },
	
	["lodObjectFadeScale"] = {},
}

local CategoryNames = { -- not sure how meaningful these really are (/Blizzard_Console/Blizzard_Console_AutoComplete.lua Enum.ConsoleCategory)
	[0] = "Debug",
	[1] = "Graphics",
	[2] = "Console",
	[3] = "Combat",
	[4] = "Game",
	[5] = "Default",
	[6] = "Net",
	[7] = "Sound",
	[8] = "GM",
	[9] = "None",
}

--[[
	C_Console.GetAllCommands() returns a list of tables in this format:
		category: number from 0 to 9 representing a category above
		command: cvar name
		commandType: 0 seems to represent a cvar, 1 is a script command (like quit)
		help: cvar description text
--]]

for _, info in pairs(C_Console.GetAllCommands()) do
	if not addon.hiddenOptions[info.command]
	  and info.commandType == 0 -- cvar, rather than script
	  and info.category ~= 0 -- ignore debug category
	  and not strfind(info.command:lower(), 'debug') -- a number of commands with "debug" in their name are inexplicibly not in the "debug" category
	  and info.category ~= 8 -- ignore GM category
	then
		local value = GetCVar(info.command)
		local optionTable = {
			-- prettyName = info.command, -- the api doesn't provide pretty names, so the only way to keep these would be to create a table for them
			description = info.help,		
		}
		addon.hiddenOptions[info.command] = optionTable
	end
end


-- Allow case-insensitive lookup of cvars in our table (relatively slow, so match the case when possible)
local NoCase = {
	__index = function(t, mk) -- get
		if mk and mk.lower then
			local mk = mk:lower()
			for k,v in pairs(t) do
				if k:lower() == mk then
					return v
				end
			end
		end
	end,
	__newindex = function(t, mk, mv) -- set
		if mk and mk.lower then
			local mk = mk:lower()
			for k,v in pairs(t) do
				if k:lower() == mk then
					t[k] = mv
					return
				end
			end
		end
	end,
}
setmetatable(addon.hiddenOptions, NoCase)